package com.beone.shg.net.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * BankAcUpload generated by vaibhav
 */
@Entity
@Table(name="bank_ac_upload"
,catalog="shg"
, uniqueConstraints = {  }
		)
public class BankAcUpload  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 1859038640347493416L;
	private long uploadId;
	private long bankAccountNo;
	private BigDecimal amount;
	private byte[] file;
	private Date uploadDate;

	// Constructors

	/** default constructor */
	public BankAcUpload() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="upload_id", unique=true, nullable=false, insertable=true, updatable=true)
	public long getUploadId() {
		return uploadId;
	}

	public void setUploadId(long uploadId) {
		this.uploadId = uploadId;
	}
	@Column(name="bank_account_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getBankAccountNo() {
		return bankAccountNo;
	}

	public void setBankAccountNo(long bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}
	@Column(name="amount", unique=false, nullable=true, insertable=true, updatable=true, precision=16)
	
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Lob
	@Column(name = "file", nullable=false, columnDefinition="mediumblob")
	public byte[] getFile() {
		return file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

	@Column(name="upload_date", unique=false, nullable=true, insertable=true, updatable=true, length=19)

	public Date getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}
}
