package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:18 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * BankAccountType generated by hbm2java
 */
@Entity
@Table(name="bank_account_type"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class BankAccountType  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 6568398736636098767L;
	private int accountTypeId;
	private String accountType;
	private String accountTypeDesc;


	// Constructors

	/** default constructor */
	public BankAccountType() {
	}

	/** minimal constructor */
	public BankAccountType(int accountTypeId, String accountType) {
		this.accountTypeId = accountTypeId;
		this.accountType = accountType;
	}

	/** minimal constructor */
	public BankAccountType(String accountType, String accountTypeDesc) {
		this.accountType = accountType;
		this.accountTypeDesc = accountTypeDesc;
	}

	/** full constructor */
	public BankAccountType(int accountTypeId, String accountType, String accountTypeDesc) {
		this.accountTypeId = accountTypeId;
		this.accountType = accountType;
		this.accountTypeDesc = accountTypeDesc;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="account_type_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getAccountTypeId() {
		return this.accountTypeId;
	}

	public void setAccountTypeId(int accountTypeId) {
		this.accountTypeId = accountTypeId;
	}
	@Column(name="account_type", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}
	@Column(name="account_type_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getAccountTypeDesc() {
		return this.accountTypeDesc;
	}

	public void setAccountTypeDesc(String accountTypeDesc) {
		this.accountTypeDesc = accountTypeDesc;
	}

}
