package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name="bank_account"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class BankAccount  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -6243812892727030281L;
	private long bankAccountNo;
	private int bankAccountTypeId;
	private BankProfile bankProfile;
	private String accountName;
	private String accountNumber;
	private String attachmentUrl;
	private Set<AdvanceCheques> advanceChequeses = new HashSet<AdvanceCheques>(0);

	// Constructors

	/** default constructor */
	public BankAccount() {
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="bank_account_no", unique=true, nullable=false, insertable=true, updatable=true)

	public long getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(long bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}
	@Column(name="account_type_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getBankAccountTypeId() {
		return this.bankAccountTypeId;
	}

	public void setBankAccountTypeId(int bankAccountTypeId) {
		this.bankAccountTypeId = bankAccountTypeId;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="b_g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public BankProfile getBankProfile() {
		return this.bankProfile;
	}

	public void setBankProfile(BankProfile bankProfile) {
		this.bankProfile = bankProfile;
	}
	@Column(name="account_name", unique=false, nullable=true, insertable=true, updatable=true, length=50)

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}
	@Column(name="account_number", unique=false, nullable=true, insertable=true, updatable=true, length=25)

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	@Column(name="attachment_url", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}
	@OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="bankAccount")

	public Set<AdvanceCheques> getAdvanceChequeses() {
		return this.advanceChequeses;
	}

	public void setAdvanceChequeses(Set<AdvanceCheques> advanceChequeses) {
		this.advanceChequeses = advanceChequeses;
	}
}
