package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Contact generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="contact"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class Contact  implements java.io.Serializable {

	// Fields    
//	private static final long serialVersionUID = -355203714575468844L;
	private long contactId;
	private District district;
	private String address;
	private String village;
	private String grampanchayat;
	private String taluka;
	private String pinCode;
	private String phone;
	private String priMobile;
	private String secMobile;
	private String email;

	// Constructors

	/** default constructor */
	public Contact() {
	}

	/** minimal constructor */
	public Contact(long contactId, District district) {
		this.contactId = contactId;
		this.district = district;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="contact_id", unique=true, nullable=false, insertable=true, updatable=true)
	public long getContactId() {
		return this.contactId;
	}

	public void setContactId(long contactId) {
		this.contactId = contactId;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="district_id", unique=false, nullable=false, insertable=true, updatable=true)

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}
	@Column(name="address", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	@Column(name="village", unique=false, nullable=true, insertable=true, updatable=true, length=25)

	public String getVillage() {
		return village;
	}

	public void setVillage(String village) {
		this.village = village;
	}
	@Column(name="grampanchayat", unique=false, nullable=true, insertable=true, updatable=true, length=25)

	public String getGrampanchayat() {
		return grampanchayat;
	}

	public void setGrampanchayat(String grampanchayat) {
		this.grampanchayat = grampanchayat;
	}
	@Column(name="taluka", unique=false, nullable=true, insertable=true, updatable=true, length=25)

	public String getTaluka() {
		return taluka;
	}

	public void setTaluka(String taluka) {
		this.taluka = taluka;
	}

	@Column(name="pin_code", unique=false, nullable=true, insertable=true, updatable=true, length=8)

	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}
	@Column(name="phone", unique=false, nullable=true, insertable=true, updatable=true, length=15)

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@Column(name="pri_mobile", unique=false, nullable=true, insertable=true, updatable=true, length=15)

	public String getPriMobile() {
		return this.priMobile;
	}

	public void setPriMobile(String priMobile) {
		this.priMobile = priMobile;
	}
	@Column(name="sec_mobile", unique=false, nullable=true, insertable=true, updatable=true, length=15)

	public String getSecMobile() {
		return this.secMobile;
	}

	public void setSecMobile(String secMobile) {
		this.secMobile = secMobile;
	}
	@Column(name="email", unique=false, nullable=true, insertable=true, updatable=true, length=40)

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}
