package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.beone.shg.net.persistence.util.DataUtil;


/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class District  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 7643594961901199686L;
	private int districtId;
	private Lang lang;
	private String state;
	private String division;
	private String district;
	private String districtCode;
	private Integer groupCounter;

	// Constructors

	/** default constructor */
	public District() {
	}

	/** minimal constructor */
	public District(Lang lang, String state, String division, String district, String districtCode) {
		this.lang = lang;
		this.state = state;
		this.division = division;
		this.district = district;
		this.districtCode = districtCode;
		this.groupCounter = DataUtil.ZERO_INTEGER;
	}

	/** full constructor */
	public District(int districtId, Lang lang, String state, String division, String district, String districtCode) {
		this.districtId = districtId;
		this.lang = lang;
		this.state = state;
		this.division = division;
		this.district = district;
		this.districtCode = districtCode;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="district_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public Lang getLang() {
		return this.lang;
	}

	public void setLang(Lang lang) {
		this.lang = lang;
	}
	@Column(name="state", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	@Column(name="division", unique=false, nullable=true, insertable=true, updatable=true, length=20)

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}
	@Column(name="district", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}
	@Column(name="district_code", unique=false, nullable=true, insertable=true, updatable=true, length=5)

	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}
	@Column(name="group_counter", unique=false, nullable=true, insertable=true, updatable=true)

	public Integer getGroupCounter() {
		return this.groupCounter;
	}

	public void setGroupCounter(Integer groupCounter) {
		this.groupCounter = groupCounter;
	}

}
