package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FundType generated by hbm2java
 */
@Entity
@Table(name="fund_type"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class FundType implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -8176740223481059248L;
	private int fundTypeId;
	private String fundType;
	private String fundCategory;
	private String fundTypeDesc;

	// Constructors

	/** default constructor */
	public FundType() {
	}

	/** full constructor */
	public FundType(String fundType, String fundCategory, String fundTypeDesc) {
		this.fundType = fundType;
		this.fundCategory = fundCategory;
		this.fundTypeDesc = fundTypeDesc;
	}

	/** full constructor */
	public FundType(int fundTypeId, String fundType, String fundCategory, String fundTypeDesc) {
		this.fundTypeId = fundTypeId;
		this.fundType = fundType;
		this.fundCategory = fundCategory;
		this.fundTypeDesc = fundTypeDesc;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="fund_type_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getFundTypeId() {
		return this.fundTypeId;
	}

	public void setFundTypeId(int fundTypeId) {
		this.fundTypeId = fundTypeId;
	}
	@Column(name="fund_type", unique=false, nullable=false, insertable=true, updatable=true, length=35)

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}
	@Column(name="fund_category", unique=false, nullable=false, insertable=true, updatable=true, length=25)

	public String getFundCategory() {
		return this.fundCategory;
	}

	public void setFundCategory(String fundCategory) {
		this.fundCategory = fundCategory;
	}
	@Column(name="fund_type_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getFundTypeDesc() {
		return this.fundTypeDesc;
	}

	public void setFundTypeDesc(String fundTypeDesc) {
		this.fundTypeDesc = fundTypeDesc;
	}
}
