package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:18 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * GAc generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="g_ac"
,catalog="shg"
		)

public class GAc  implements java.io.Serializable {
	// Fields    

	private long GAcNo;
	private float creditRating;
	private float approvalRating;
	private float meetingAttendance;
	private BigDecimal CMPlannedMonthlySaving;
	private BigDecimal CMSavedAm;
	private BigDecimal CMOutstandingSavedAm;
	private BigDecimal CMReturnedSavedAm;
	private BigDecimal CMReturnedIntEnAm;
	private BigDecimal CMProfitShareDeclaredAm;
	private BigDecimal CMProfitSharePaidAm;
	private BigDecimal CMProvIntEnAm;
	private int CMNoOfLoans;
	private int CMNoOfActiveLoans;
	private BigDecimal CMLoanAm;
	private BigDecimal CMRecLoanAm;
	private BigDecimal CMRecIntOnLoanAm;
	private BigDecimal CMProjIntOnLoanAm;
	private BigDecimal CMSubStdDeptAm;
	private int CMNoOfSubStdDept;
	private BigDecimal CMBadDeptExpAm;
	private int CMNoOfBadDeptExp;
	private BigDecimal CMBadDeptClosedAm;
	private int CMNoOfBadDeptClosed;
	private BigDecimal AMPlannedMonthlySaving;
	private BigDecimal AMSavedAm;
	private BigDecimal AMOutstandingSavedAm;
	private BigDecimal AMProvIntEnAm;
	private BigDecimal AMReturnedSavedAm;
	private BigDecimal AMReturnedIntEnAm;
	private BigDecimal AMDividedDeclaredAm;
	private BigDecimal AMDividedPaidAm;
	private int AMNoOfLoans;
	private int AMNoOfActiveLoans;
	private BigDecimal AMLoanAm;
	private BigDecimal AMRecLoanAm;
	private BigDecimal AMRecIntOnLoanAm;
	private BigDecimal AMProjIntOnLoanAm;
	private BigDecimal AMSubStdDeptAm;
	private int AMNoOfSubStdDept;
	private BigDecimal AMBadDeptExpAm;
	private int AMNoOfBadDeptExp;
	private BigDecimal AMBadDeptClosedAm;
	private int AMNoOfBadDeptClosed;
	private BigDecimal PLoanAm;
	private BigDecimal PRecLoanAm;
	private BigDecimal PRecIntOnLoanAm;
	private BigDecimal PProjIntOnLoanAm;
	private int noOfProject;
	private int noOfActiveProject;
	private BigDecimal fixDepositInvAm;
	private BigDecimal recFixDepositAm;
	private BigDecimal recIntOnFixDepositAm;
	private BigDecimal projIntOnFixDepositAm;
	private int noOfFixDeposit;
	private int noOfActiveFixDeposit;
	private BigDecimal otherInvAm;
	private BigDecimal recOtherInvAm;
	private BigDecimal recIntOnOtherInvAm;
	private BigDecimal projIntOnOtherInvAm;
	private int noOfOtherInv;
	private int noOfActiveOtherInv;
	private BigDecimal intEnOnSavingAcAm;
	private BigDecimal clearBankBalanceAm;
	private BigDecimal subjClearingBankBalanceAm;
	private BigDecimal clearCashInHandAm;
	private BigDecimal subjClearingCashInHandAm;
	private BigDecimal netProfitAm;
	private BigDecimal netProfitProjAm;
	private BigDecimal expensesAm;
	private BigDecimal outstandingExpensesAm;
	private BigDecimal recPenaltyAm;
	private BigDecimal pendingPenaltyAm;
	private BigDecimal borrowedLoanAm;
	private BigDecimal paidBorrowedLoanAm;
	private BigDecimal paidIntOnBorrowedLoanAm;
	private BigDecimal projIntOnBorrowedLoanAm;
	private BigDecimal bankSubStdDeptAm;
	private int bankNoOfSubStdDept;
	private BigDecimal bankBadDeptExpAm;
	private int bankNoOfBadDeptExp;
	private BigDecimal bankBadDeptClosedAm;
	private int bankNoOfBadDeptClosed;
	private int noOfBankLoan;
	private int noOfActiveBankLoan;
	private BigDecimal govRevolvingFundAm;
	private BigDecimal govRevolvingFundReturnedAm;
	private int noOfGovRevolvingFund;
	private int noOfActiveGovRevolvingFund;
	private BigDecimal govDevelopmentFundAm;
	private int noOfGovDevelopmentFund;
	private BigDecimal penShgOneMemRegFee;
	private BigDecimal penShgOneServiceCharges;
	private int noOfTxsMonthlyExp;
	private int noOfTxsMonthlyDone;
	private int noOfTxsMonthlyApproved;
	private Date lastUpdatedTs;

	private GProfile GProfile;
	private Set<GInvtAc> GInvtAcs = new HashSet<GInvtAc>(0);
	private Set<GLoanAc> GLoanAcs = new HashSet<GLoanAc>(0);

	// Constructors

	/** default constructor */
	public GAc() {
	}

	/** minimal constructor */
	public GAc(long GAcNo) {
		this.GAcNo = GAcNo;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GroupAcIdGenerator")
	@GenericGenerator(name = "GroupAcIdGenerator", strategy = "com.beone.shg.net.persistence.generator.GroupAcIdGenerator")
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getGAcNo() {
		return this.GAcNo;
	}

	public void setGAcNo(long GAcNo) {
		this.GAcNo = GAcNo;
	}
	@Column(name="credit_rating", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCreditRating() {
		return this.creditRating;
	}

	public void setCreditRating(float creditRating) {
		this.creditRating = creditRating;
	}
	@Column(name="approval_rating", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getApprovalRating() {
		return this.approvalRating;
	}

	public void setApprovalRating(float approvalRating) {
		this.approvalRating = approvalRating;
	}
	@Column(name="meeting_attendance", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getMeetingAttendance() {
		return this.meetingAttendance;
	}

	public void setMeetingAttendance(float meetingAttendance) {
		this.meetingAttendance = meetingAttendance;
	}
	@Column(name="c_m_planned_monthly_saving", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMPlannedMonthlySaving() {
		return CMPlannedMonthlySaving;
	}

	public void setCMPlannedMonthlySaving(BigDecimal CMPlannedMonthlySaving) {
		this.CMPlannedMonthlySaving = CMPlannedMonthlySaving;
	}
	@Column(name="c_m_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMSavedAm() {
		return this.CMSavedAm;
	}

	public void setCMSavedAm(BigDecimal CMSavedAm) {
		this.CMSavedAm = CMSavedAm;
	}

	@Column(name="c_m_outstanding_saving_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMOutstandingSavedAm() {
		return CMOutstandingSavedAm;
	}

	public void setCMOutstandingSavedAm(BigDecimal cMOutstandingSavedAm) {
		CMOutstandingSavedAm = cMOutstandingSavedAm;
	}

	@Column(name="c_m_returned_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMReturnedSavedAm() {
		return this.CMReturnedSavedAm;
	}

	public void setCMReturnedSavedAm(BigDecimal CMReturnedSavedAm) {
		this.CMReturnedSavedAm = CMReturnedSavedAm;
	}
	@Column(name="c_m_returned_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMReturnedIntEnAm() {
		return this.CMReturnedIntEnAm;
	}

	public void setCMReturnedIntEnAm(BigDecimal CMReturnedIntEnAm) {
		this.CMReturnedIntEnAm = CMReturnedIntEnAm;
	}
	@Column(name="c_m_profit_share_declared_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMProfitShareDeclaredAm() {
		return this.CMProfitShareDeclaredAm;
	}

	public void setCMProfitShareDeclaredAm(BigDecimal CMProfitShareDeclaredAm) {
		this.CMProfitShareDeclaredAm = CMProfitShareDeclaredAm;
	}
	@Column(name="c_m_profit_share_paid_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMProfitSharePaidAm() {
		return this.CMProfitSharePaidAm;
	}

	public void setCMProfitSharePaidAm(BigDecimal CMProfitSharePaidAm) {
		this.CMProfitSharePaidAm = CMProfitSharePaidAm;
	}
	@Column(name="c_m_prov_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMProvIntEnAm() {
		return this.CMProvIntEnAm;
	}

	public void setCMProvIntEnAm(BigDecimal CMProvIntEnAm) {
		this.CMProvIntEnAm = CMProvIntEnAm;
	}
	@Column(name="c_m_no_of_loans", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCMNoOfLoans() {
		return CMNoOfLoans;
	}

	public void setCMNoOfLoans(int cMNoOfLoans) {
		CMNoOfLoans = cMNoOfLoans;
	}
	@Column(name="c_m_no_of_active_loans", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCMNoOfActiveLoans() {
		return CMNoOfActiveLoans;
	}

	public void setCMNoOfActiveLoans(int cMNoOfActiveLoans) {
		CMNoOfActiveLoans = cMNoOfActiveLoans;
	}

	@Column(name="c_m_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMLoanAm() {
		return this.CMLoanAm;
	}

	public void setCMLoanAm(BigDecimal CMLoanAm) {
		this.CMLoanAm = CMLoanAm;
	}
	@Column(name="c_m_rec_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMRecLoanAm() {
		return this.CMRecLoanAm;
	}

	public void setCMRecLoanAm(BigDecimal CMRecLoanAm) {
		this.CMRecLoanAm = CMRecLoanAm;
	}
	@Column(name="c_m_rec_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMRecIntOnLoanAm() {
		return this.CMRecIntOnLoanAm;
	}

	public void setCMRecIntOnLoanAm(BigDecimal CMRecIntOnLoanAm) {
		this.CMRecIntOnLoanAm = CMRecIntOnLoanAm;
	}
	@Column(name="c_m_proj_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMProjIntOnLoanAm() {
		return this.CMProjIntOnLoanAm;
	}

	public void setCMProjIntOnLoanAm(BigDecimal CMProjIntOnLoanAm) {
		this.CMProjIntOnLoanAm = CMProjIntOnLoanAm;
	}
	@Column(name="c_m_sub_std_dept_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMSubStdDeptAm() {
		return CMSubStdDeptAm;
	}

	public void setCMSubStdDeptAm(BigDecimal cMSubStdDeptAm) {
		CMSubStdDeptAm = cMSubStdDeptAm;
	}
	@Column(name="c_m_no_of_sub_std_dept", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public int getCMNoOfSubStdDept() {
		return CMNoOfSubStdDept;
	}

	public void setCMNoOfSubStdDept(int cMNoOfSubStdDept) {
		CMNoOfSubStdDept = cMNoOfSubStdDept;
	}
	@Column(name="c_m_bad_dept_exp_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMBadDeptExpAm() {
		return CMBadDeptExpAm;
	}

	public void setCMBadDeptExpAm(BigDecimal cMBadDeptExpAm) {
		CMBadDeptExpAm = cMBadDeptExpAm;
	}
	@Column(name="c_m_no_of_bad_dept_exp", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public int getCMNoOfBadDeptExp() {
		return CMNoOfBadDeptExp;
	}

	public void setCMNoOfBadDeptExp(int cMNoOfBadDeptExp) {
		CMNoOfBadDeptExp = cMNoOfBadDeptExp;
	}
	@Column(name="c_m_bad_dept_closed_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCMBadDeptClosedAm() {
		return CMBadDeptClosedAm;
	}

	public void setCMBadDeptClosedAm(BigDecimal cMBadDeptClosedAm) {
		CMBadDeptClosedAm = cMBadDeptClosedAm;
	}
	@Column(name="c_m_no_of_bad_dept_closed", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCMNoOfBadDeptClosed() {
		return CMNoOfBadDeptClosed;
	}

	public void setCMNoOfBadDeptClosed(int CMNoOfBadDeptClosed) {
		this.CMNoOfBadDeptClosed = CMNoOfBadDeptClosed;
	}

	@Column(name="a_m_planned_monthly_saving", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMPlannedMonthlySaving() {
		return AMPlannedMonthlySaving;
	}

	public void setAMPlannedMonthlySaving(BigDecimal AMPlannedMonthlySaving) {
		this.AMPlannedMonthlySaving = AMPlannedMonthlySaving;
	}
	@Column(name="a_m_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMSavedAm() {
		return this.AMSavedAm;
	}

	public void setAMSavedAm(BigDecimal AMSavedAm) {
		this.AMSavedAm = AMSavedAm;
	}

	@Column(name="a_m_outstanding_saving_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMOutstandingSavedAm() {
		return AMOutstandingSavedAm;
	}

	public void setAMOutstandingSavedAm(BigDecimal aMOutstandingSavedAm) {
		AMOutstandingSavedAm = aMOutstandingSavedAm;
	}

	@Column(name="a_m_prov_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMProvIntEnAm() {
		return this.AMProvIntEnAm;
	}

	public void setAMProvIntEnAm(BigDecimal AMProvIntEnAm) {
		this.AMProvIntEnAm = AMProvIntEnAm;
	}
	@Column(name="a_m_returned_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMReturnedSavedAm() {
		return this.AMReturnedSavedAm;
	}

	public void setAMReturnedSavedAm(BigDecimal AMReturnedSavedAm) {
		this.AMReturnedSavedAm = AMReturnedSavedAm;
	}
	@Column(name="a_m_returned_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMReturnedIntEnAm() {
		return this.AMReturnedIntEnAm;
	}

	public void setAMReturnedIntEnAm(BigDecimal AMReturnedIntEnAm) {
		this.AMReturnedIntEnAm = AMReturnedIntEnAm;
	}
	@Column(name="a_m_divided_declared_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMDividedDeclaredAm() {
		return this.AMDividedDeclaredAm;
	}

	public void setAMDividedDeclaredAm(BigDecimal AMDividedDeclaredAm) {
		this.AMDividedDeclaredAm = AMDividedDeclaredAm;
	}
	@Column(name="a_m_divided_paid_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMDividedPaidAm() {
		return this.AMDividedPaidAm;
	}

	public void setAMDividedPaidAm(BigDecimal AMDividedPaidAm) {
		this.AMDividedPaidAm = AMDividedPaidAm;
	}
	@Column(name="a_m_no_of_loans", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAMNoOfLoans() {
		return AMNoOfLoans;
	}

	public void setAMNoOfLoans(int aMNoOfLoans) {
		AMNoOfLoans = aMNoOfLoans;
	}
	@Column(name="a_m_no_of_active_loans", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAMNoOfActiveLoans() {
		return AMNoOfActiveLoans;
	}

	public void setAMNoOfActiveLoans(int aMNoOfActiveLoans) {
		AMNoOfActiveLoans = aMNoOfActiveLoans;
	}

	@Column(name="a_m_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMLoanAm() {
		return this.AMLoanAm;
	}

	public void setAMLoanAm(BigDecimal AMLoanAm) {
		this.AMLoanAm = AMLoanAm;
	}
	@Column(name="a_m_rec_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMRecLoanAm() {
		return this.AMRecLoanAm;
	}

	public void setAMRecLoanAm(BigDecimal AMRecLoanAm) {
		this.AMRecLoanAm = AMRecLoanAm;
	}
	@Column(name="a_m_rec_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMRecIntOnLoanAm() {
		return this.AMRecIntOnLoanAm;
	}

	public void setAMRecIntOnLoanAm(BigDecimal AMRecIntOnLoanAm) {
		this.AMRecIntOnLoanAm = AMRecIntOnLoanAm;
	}
	@Column(name="a_m_proj_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMProjIntOnLoanAm() {
		return this.AMProjIntOnLoanAm;
	}

	public void setAMProjIntOnLoanAm(BigDecimal AMProjIntOnLoanAm) {
		this.AMProjIntOnLoanAm = AMProjIntOnLoanAm;
	}
	@Column(name="a_m_sub_std_dept_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMSubStdDeptAm() {
		return AMSubStdDeptAm;
	}

	public void setAMSubStdDeptAm(BigDecimal aMSubStdDeptAm) {
		AMSubStdDeptAm = aMSubStdDeptAm;
	}
	@Column(name="a_m_no_of_sub_std_dept", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAMNoOfSubStdDept() {
		return AMNoOfSubStdDept;
	}

	public void setAMNoOfSubStdDept(int aMNoOfSubStdDept) {
		AMNoOfSubStdDept = aMNoOfSubStdDept;
	}
	@Column(name="a_m_bad_dept_exp_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMBadDeptExpAm() {
		return AMBadDeptExpAm;
	}

	public void setAMBadDeptExpAm(BigDecimal aMBadDeptExpAm) {
		AMBadDeptExpAm = aMBadDeptExpAm;
	}
	@Column(name="a_m_no_of_bad_dept_exp", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAMNoOfBadDeptExp() {
		return AMNoOfBadDeptExp;
	}

	public void setAMNoOfBadDeptExp(int aMNoOfBadDeptExp) {
		AMNoOfBadDeptExp = aMNoOfBadDeptExp;
	}
	@Column(name="a_m_bad_dept_closed_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAMBadDeptClosedAm() {
		return AMBadDeptClosedAm;
	}

	public void setAMBadDeptClosedAm(BigDecimal aMBadDeptClosedAm) {
		AMBadDeptClosedAm = aMBadDeptClosedAm;
	}
	@Column(name="a_m_no_of_bad_dept_closed", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAMNoOfBadDeptClosed() {
		return AMNoOfBadDeptClosed;
	}

	public void setAMNoOfBadDeptClosed(int AMNoOfBadDeptClosed) {
		this.AMNoOfBadDeptClosed = AMNoOfBadDeptClosed;
	}

	@Column(name="p_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPLoanAm() {
		return this.PLoanAm;
	}

	public void setPLoanAm(BigDecimal PLoanAm) {
		this.PLoanAm = PLoanAm;
	}
	@Column(name="p_rec_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPRecLoanAm() {
		return this.PRecLoanAm;
	}

	public void setPRecLoanAm(BigDecimal PRecLoanAm) {
		this.PRecLoanAm = PRecLoanAm;
	}
	@Column(name="p_rec_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPRecIntOnLoanAm() {
		return this.PRecIntOnLoanAm;
	}

	public void setPRecIntOnLoanAm(BigDecimal PRecIntOnLoanAm) {
		this.PRecIntOnLoanAm = PRecIntOnLoanAm;
	}
	@Column(name="p_proj_int_on_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPProjIntOnLoanAm() {
		return this.PProjIntOnLoanAm;
	}

	public void setPProjIntOnLoanAm(BigDecimal PProjIntOnLoanAm) {
		this.PProjIntOnLoanAm = PProjIntOnLoanAm;
	}
	@Column(name="no_of_project", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfProject() {
		return noOfProject;
	}

	public void setNoOfProject(int noOfProject) {
		this.noOfProject = noOfProject;
	}
	@Column(name="no_of_active_project", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfActiveProject() {
		return noOfActiveProject;
	}

	public void setNoOfActiveProject(int noOfActiveProject) {
		this.noOfActiveProject = noOfActiveProject;
	}

	@Column(name="fix_deposit_inv_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getFixDepositInvAm() {
		return this.fixDepositInvAm;
	}

	public void setFixDepositInvAm(BigDecimal fixDepositInvAm) {
		this.fixDepositInvAm = fixDepositInvAm;
	}
	@Column(name="rec_fix_deposit_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecFixDepositAm() {
		return this.recFixDepositAm;
	}

	public void setRecFixDepositAm(BigDecimal recFixDepositAm) {
		this.recFixDepositAm = recFixDepositAm;
	}
	@Column(name="rec_int_on_fix_deposit_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecIntOnFixDepositAm() {
		return this.recIntOnFixDepositAm;
	}

	public void setRecIntOnFixDepositAm(BigDecimal recIntOnFixDepositAm) {
		this.recIntOnFixDepositAm = recIntOnFixDepositAm;
	}
	@Column(name="proj_int_on_fix_deposit_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjIntOnFixDepositAm() {
		return this.projIntOnFixDepositAm;
	}

	public void setProjIntOnFixDepositAm(BigDecimal projIntOnFixDepositAm) {
		this.projIntOnFixDepositAm = projIntOnFixDepositAm;
	}
	@Column(name="no_of_fix_deposit", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfFixDeposit() {
		return noOfFixDeposit;
	}

	public void setNoOfFixDeposit(int noOfFixDeposit) {
		this.noOfFixDeposit = noOfFixDeposit;
	}
	@Column(name="no_of_active_fix_deposit", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfActiveFixDeposit() {
		return noOfActiveFixDeposit;
	}

	public void setNoOfActiveFixDeposit(int noOfActiveFixDeposit) {
		this.noOfActiveFixDeposit = noOfActiveFixDeposit;
	}

	@Column(name="other_inv_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getOtherInvAm() {
		return this.otherInvAm;
	}

	public void setOtherInvAm(BigDecimal otherInvAm) {
		this.otherInvAm = otherInvAm;
	}
	@Column(name="rec_other_inv_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecOtherInvAm() {
		return this.recOtherInvAm;
	}

	public void setRecOtherInvAm(BigDecimal recOtherInvAm) {
		this.recOtherInvAm = recOtherInvAm;
	}
	@Column(name="rec_int_on_other_inv_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecIntOnOtherInvAm() {
		return this.recIntOnOtherInvAm;
	}

	public void setRecIntOnOtherInvAm(BigDecimal recIntOnOtherInvAm) {
		this.recIntOnOtherInvAm = recIntOnOtherInvAm;
	}
	@Column(name="proj_int_on_other_inv_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjIntOnOtherInvAm() {
		return this.projIntOnOtherInvAm;
	}

	public void setProjIntOnOtherInvAm(BigDecimal projIntOnOtherInvAm) {
		this.projIntOnOtherInvAm = projIntOnOtherInvAm;
	}
	@Column(name="no_of_other_inv", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfOtherInv() {
		return noOfOtherInv;
	}

	public void setNoOfOtherInv(int noOfOtherInv) {
		this.noOfOtherInv = noOfOtherInv;
	}
	@Column(name="no_of_active_other_inv", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfActiveOtherInv() {
		return noOfActiveOtherInv;
	}

	public void setNoOfActiveOtherInv(int noOfActiveOtherInv) {
		this.noOfActiveOtherInv = noOfActiveOtherInv;
	}

	@Column(name="int_en_on_saving_ac_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getIntEnOnSavingAcAm() {
		return this.intEnOnSavingAcAm;
	}

	public void setIntEnOnSavingAcAm(BigDecimal intEnOnSavingAcAm) {
		this.intEnOnSavingAcAm = intEnOnSavingAcAm;
	}
	@Column(name="clear_bank_balance_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getClearBankBalanceAm() {
		return this.clearBankBalanceAm;
	}

	public void setClearBankBalanceAm(BigDecimal clearBankBalanceAm) {
		this.clearBankBalanceAm = clearBankBalanceAm;
	}
	@Column(name="subj_clearing_bank_balance_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getSubjClearingBankBalanceAm() {
		return this.subjClearingBankBalanceAm;
	}

	public void setSubjClearingBankBalanceAm(BigDecimal subjClearingBankBalanceAm) {
		this.subjClearingBankBalanceAm = subjClearingBankBalanceAm;
	}
	@Column(name="clear_cash_in_hand_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getClearCashInHandAm() {
		return this.clearCashInHandAm;
	}

	public void setClearCashInHandAm(BigDecimal clearCashInHandAm) {
		this.clearCashInHandAm = clearCashInHandAm;
	}
	@Column(name="net_profit_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getNetProfitAm() {
		return this.netProfitAm;
	}

	public void setNetProfitAm(BigDecimal netProfitAm) {
		this.netProfitAm = netProfitAm;
	}
	@Column(name="net_profit_proj_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getNetProfitProjAm() {
		return netProfitProjAm;
	}

	public void setNetProfitProjAm(BigDecimal netProfitProjAm) {
		this.netProfitProjAm = netProfitProjAm;
	}

	@Column(name="expenses_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getExpensesAm() {
		return this.expensesAm;
	}

	public void setExpensesAm(BigDecimal expensesAm) {
		this.expensesAm = expensesAm;
	}

	@Column(name="outstanding_expenses_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getOutstandingExpensesAm() {
		return outstandingExpensesAm;
	}

	public void setOutstandingExpensesAm(BigDecimal outstandingExpensesAm) {
		this.outstandingExpensesAm = outstandingExpensesAm;
	}

	@Column(name="rec_penalty_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecPenaltyAm() {
		return this.recPenaltyAm;
	}

	public void setRecPenaltyAm(BigDecimal recPenaltyAm) {
		this.recPenaltyAm = recPenaltyAm;
	}
	@Column(name="pending_penalty_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPendingPenaltyAm() {
		return this.pendingPenaltyAm;
	}

	public void setPendingPenaltyAm(BigDecimal pendingPenaltyAm) {
		this.pendingPenaltyAm = pendingPenaltyAm;
	}
	@Column(name="subj_clearing_cash_in_hand_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getSubjClearingCashInHandAm() {
		return this.subjClearingCashInHandAm;
	}

	public void setSubjClearingCashInHandAm(BigDecimal subjClearingCashInHandAm) {
		this.subjClearingCashInHandAm = subjClearingCashInHandAm;
	}
	@Column(name="borrowed_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getBorrowedLoanAm() {
		return borrowedLoanAm;
	}

	public void setBorrowedLoanAm(BigDecimal borrowedLoanAm) {
		this.borrowedLoanAm = borrowedLoanAm;
	}
	@Column(name="paid_borrowed_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPaidBorrowedLoanAm() {
		return paidBorrowedLoanAm;
	}

	public void setPaidBorrowedLoanAm(BigDecimal paidBorrowedLoanAm) {
		this.paidBorrowedLoanAm = paidBorrowedLoanAm;
	}
	@Column(name="paid_int_on_borrowed_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPaidIntOnBorrowedLoanAm() {
		return paidIntOnBorrowedLoanAm;
	}

	public void setPaidIntOnBorrowedLoanAm(BigDecimal paidIntOnBorrowedLoanAm) {
		this.paidIntOnBorrowedLoanAm = paidIntOnBorrowedLoanAm;
	}
	@Column(name="proj_int_on_borrowed_loan_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjIntOnBorrowedLoanAm() {
		return projIntOnBorrowedLoanAm;
	}

	public void setProjIntOnBorrowedLoanAm(BigDecimal projIntOnBorrowedLoanAm) {
		this.projIntOnBorrowedLoanAm = projIntOnBorrowedLoanAm;
	}
	@Column(name="bank_sub_std_dept_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getBankSubStdDeptAm() {
		return bankSubStdDeptAm;
	}

	public void setBankSubStdDeptAm(BigDecimal bankSubStdDeptAm) {
		this.bankSubStdDeptAm = bankSubStdDeptAm;
	}
	@Column(name="bank_no_of_sub_std_dept", unique=false, nullable=true, insertable=true, updatable=true)

	public int getBankNoOfSubStdDept() {
		return bankNoOfSubStdDept;
	}

	public void setBankNoOfSubStdDept(int bankNoOfSubStdDept) {
		this.bankNoOfSubStdDept = bankNoOfSubStdDept;
	}
	@Column(name="bank_bad_dept_exp_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getBankBadDeptExpAm() {
		return bankBadDeptExpAm;
	}

	public void setBankBadDeptExpAm(BigDecimal bankBadDeptExpAm) {
		this.bankBadDeptExpAm = bankBadDeptExpAm;
	}
	@Column(name="bank_no_of_bad_dept_exp", unique=false, nullable=true, insertable=true, updatable=true)

	public int getBankNoOfBadDeptExp() {
		return bankNoOfBadDeptExp;
	}

	public void setBankNoOfBadDeptExp(int bankNoOfBadDeptExp) {
		this.bankNoOfBadDeptExp = bankNoOfBadDeptExp;
	}
	@Column(name="bank_bad_dept_closed_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getBankBadDeptClosedAm() {
		return bankBadDeptClosedAm;
	}

	public void setBankBadDeptClosedAm(BigDecimal bankBadDeptClosedAm) {
		this.bankBadDeptClosedAm = bankBadDeptClosedAm;
	}
	@Column(name="bank_no_of_bad_dept_closed", unique=false, nullable=true, insertable=true, updatable=true)

	public int getBankNoOfBadDeptClosed() {
		return bankNoOfBadDeptClosed;
	}

	public void setBankNoOfBadDeptClosed(int bankNoOfBadDeptClosed) {
		this.bankNoOfBadDeptClosed = bankNoOfBadDeptClosed;
	}
	@Column(name="no_of_bank_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfBankLoan() {
		return noOfBankLoan;
	}

	public void setNoOfBankLoan(int noOfBankLoan) {
		this.noOfBankLoan = noOfBankLoan;
	}
	@Column(name="no_of_active_bank_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfActiveBankLoan() {
		return noOfActiveBankLoan;
	}

	public void setNoOfActiveBankLoan(int noOfActiveBankLoan) {
		this.noOfActiveBankLoan = noOfActiveBankLoan;
	}
	@Column(name="gov_revolving_fund_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getGovRevolvingFundAm() {
		return govRevolvingFundAm;
	}

	public void setGovRevolvingFundAm(BigDecimal govRevolvingFundAm) {
		this.govRevolvingFundAm = govRevolvingFundAm;
	}
	@Column(name="gov_revolving_fund_returned_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getGovRevolvingFundReturnedAm() {
		return govRevolvingFundReturnedAm;
	}

	public void setGovRevolvingFundReturnedAm(BigDecimal govRevolvingFundReturnedAm) {
		this.govRevolvingFundReturnedAm = govRevolvingFundReturnedAm;
	}
	@Column(name="no_of_gov_revolving_fund", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfGovRevolvingFund() {
		return noOfGovRevolvingFund;
	}

	public void setNoOfGovRevolvingFund(int noOfGovRevolvingFund) {
		this.noOfGovRevolvingFund = noOfGovRevolvingFund;
	}
	@Column(name="no_of_active_gov_revolving_fund", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfActiveGovRevolvingFund() {
		return noOfActiveGovRevolvingFund;
	}

	public void setNoOfActiveGovRevolvingFund(int noOfActiveGovRevolvingFund) {
		this.noOfActiveGovRevolvingFund = noOfActiveGovRevolvingFund;
	}
	@Column(name="gov_development_fund_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getGovDevelopmentFundAm() {
		return govDevelopmentFundAm;
	}

	public void setGovDevelopmentFundAm(BigDecimal govDevelopmentFundAm) {
		this.govDevelopmentFundAm = govDevelopmentFundAm;
	}
	@Column(name="no_of_gov_development_fund", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfGovDevelopmentFund() {
		return noOfGovDevelopmentFund;
	}

	public void setNoOfGovDevelopmentFund(int noOfGovDevelopmentFund) {
		this.noOfGovDevelopmentFund = noOfGovDevelopmentFund;
	}

	@Column(name="pen_shg_one_mem_reg_fee", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPenShgOneMemRegFee() {
		return penShgOneMemRegFee;
	}

	public void setPenShgOneMemRegFee(BigDecimal penShgOneMemRegFee) {
		this.penShgOneMemRegFee = penShgOneMemRegFee;
	}
	@Column(name="pen_shg_one_service_charges", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPenShgOneServiceCharges() {
		return penShgOneServiceCharges;
	}

	public void setPenShgOneServiceCharges(BigDecimal penShgOneServiceCharges) {
		this.penShgOneServiceCharges = penShgOneServiceCharges;
	}
	@Column(name="no_of_txs_monthly_exp", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfTxsMonthlyExp() {
		return noOfTxsMonthlyExp;
	}

	public void setNoOfTxsMonthlyExp(int noOfTxsMonthlyExp) {
		this.noOfTxsMonthlyExp = noOfTxsMonthlyExp;
	}
	@Column(name="no_of_txs_monthly_done", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfTxsMonthlyDone() {
		return noOfTxsMonthlyDone;
	}

	public void setNoOfTxsMonthlyDone(int noOfTxsMonthlyDone) {
		this.noOfTxsMonthlyDone = noOfTxsMonthlyDone;
	}
	@Column(name="no_of_txs_monthly_approved", unique=false, nullable=true, insertable=true, updatable=true)

	public int getNoOfTxsMonthlyApproved() {
		return noOfTxsMonthlyApproved;
	}

	public void setNoOfTxsMonthlyApproved(int noOfTxsMonthlyApproved) {
		this.noOfTxsMonthlyApproved = noOfTxsMonthlyApproved;
	}

	@Column(name="last_updated_ts", unique=false, nullable=true, insertable=true, updatable=true, length=19)

	public Date getLastUpdatedTs() {
		return this.lastUpdatedTs;
	}

	public void setLastUpdatedTs(Date lastUpdatedTs) {
		this.lastUpdatedTs = lastUpdatedTs;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public GProfile getGProfile() {
		return this.GProfile;
	}

	public void setGProfile(GProfile GProfile) {
		this.GProfile = GProfile;
	}
	@OneToMany(cascade={CascadeType.REMOVE}, fetch=FetchType.EAGER, mappedBy="GAc")

	public Set<GInvtAc> getGInvtAcs() {
		return this.GInvtAcs;
	}

	public void setGInvtAcs(Set<GInvtAc> GInvtAcs) {
		this.GInvtAcs = GInvtAcs;
	}
	@OneToMany(cascade={CascadeType.REMOVE}, fetch=FetchType.EAGER, mappedBy="GAc")

	public Set<GLoanAc> getGLoanAcs() {
		return this.GLoanAcs;
	}

	public void setGLoanAcs(Set<GLoanAc> GLoanAcs) {
		this.GLoanAcs = GLoanAcs;
	}
}
