package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GAcByTxtype generated by hbm2java
 */
@Entity
@Table(name="g_ac_by_txtype"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class GAcByTxtype  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 6315940176107212531L;
	private GAcByTxtypeId id;
	private long groupAcNo;
	private int txTypeId;
	private BigDecimal amount;

	// Constructors

	/** default constructor */
	public GAcByTxtype() {
	}

	/** minimal constructor */
	public GAcByTxtype(GAcByTxtypeId id, long groupAcNo, int txTypeId) {
		this.id = id;
		this.groupAcNo = groupAcNo;
		this.txTypeId = txTypeId;
	}

	/** full constructor */
	public GAcByTxtype(GAcByTxtypeId id, long groupAcNo, int txTypeId, BigDecimal amount) {
		this.id = id;
		this.groupAcNo = groupAcNo;
		this.txTypeId = txTypeId;
		this.amount = amount;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="groupAcNo", column=@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="txTypeId", column=@Column(name="tx_type_id", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public GAcByTxtypeId getId() {
		return this.id;
	}

	public void setId(GAcByTxtypeId id) {
		this.id = id;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getGroupAcNo() {
		return this.groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
	@Column(name="tx_type_id", unique=false, nullable=false, insertable=false, updatable=false)

	public int getTxTypeId() {
		return this.txTypeId;
	}

	public void setTxTypeId(int txTypeId) {
		this.txTypeId = txTypeId;
	}
	@Column(name="amount", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}   
}
