package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:18 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * GBankAccount generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="g_bank_account"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class GBankAccount  implements java.io.Serializable {


	// Fields    
//	private static final long serialVersionUID = 9133177099045781095L;
	private long bankAccountNo;
	private GProfile GProfile;
	private BankAccount bankAccount;
	private BigDecimal clearBalanceAm;
	private BigDecimal subjClearingBalanceAm;
	private BigDecimal verifiedBalanceAm;
	private BigDecimal interestAm;
	private BigDecimal penaltyChargesAm;

	// Constructors

	/** default constructor */
	public GBankAccount() {
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GBankAccountIdGenerator")
	@GenericGenerator(name = "GBankAccountIdGenerator", strategy = "com.beone.shg.net.persistence.generator.GBankAccountIdGenerator")
	@Column(name="bank_account_no", unique=true, nullable=false, insertable=true, updatable=true)

	public long getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(long bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public GProfile getGProfile() {
		return this.GProfile;
	}

	public void setGProfile(GProfile GProfile) {
		this.GProfile = GProfile;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="bank_account_no", unique=true, nullable=false, insertable=false, updatable=false)

	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}
	@Column(name="clear_balance_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getClearBalanceAm() {
		return this.clearBalanceAm;
	}

	public void setClearBalanceAm(BigDecimal clearBalanceAm) {
		this.clearBalanceAm = clearBalanceAm;
	}
	@Column(name="subj_clearing_balance_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getSubjClearingBalanceAm() {
		return this.subjClearingBalanceAm;
	}

	public void setSubjClearingBalanceAm(BigDecimal subjClearingBalanceAm) {
		this.subjClearingBalanceAm = subjClearingBalanceAm;
	}
	@Column(name="verified_balance_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)
	
	public BigDecimal getVerifiedBalanceAm() {
		return verifiedBalanceAm;
	}

	public void setVerifiedBalanceAm(BigDecimal verifiedBalanceAm) {
		this.verifiedBalanceAm = verifiedBalanceAm;
	}
	@Column(name="interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getInterestAm() {
		return interestAm;
	}

	public void setInterestAm(BigDecimal interestAm) {
		this.interestAm = interestAm;
	}
	@Column(name="penalty_charges_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPenaltyChargesAm() {
		return penaltyChargesAm;
	}

	public void setPenaltyChargesAm(BigDecimal penaltyChargesAm) {
		this.penaltyChargesAm = penaltyChargesAm;
	}
}
