package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ParentChildGroup generated by hbm2java
 */
@Entity
@Table(name="g_g"
,catalog="shg"
		)

public class GG  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -3882734515309463645L;
	private GGId id;
	private long topGroupAcNo;
	private long downGroupAcNo;
	private int groupRelationId;
	private long wsAccessRights;
	private long uiAccessRights;

	// Constructors

	/** default constructor */
	public GG() {
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="topGroupAcNo", column=@Column(name="top_g_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="downGroupAcNo", column=@Column(name="down_g_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public GGId getId() {
		return this.id;
	}

	public void setId(GGId id) {
		this.id = id;
	}
	@Column(name="top_g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getTopGroupAcNo() {
		return this.topGroupAcNo;
	}

	public void setTopGroupAcNo(long topGroupAcNo) {
		this.topGroupAcNo = topGroupAcNo;
	}
	@Column(name="down_g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getDownGroupAcNo() {
		return this.downGroupAcNo;
	}

	public void setDownGroupAcNo(long downGroupAcNo) {
		this.downGroupAcNo = downGroupAcNo;
	}
	@Column(name="group_relation_id", unique=false, nullable=false, insertable=false, updatable=false)

	public int getGroupRelationId() {
		return this.groupRelationId;
	}

	public void setGroupRelationId(int groupRelationId) {
		this.groupRelationId = groupRelationId;
	}
	@Column(name="ws_access_rights", unique=false, nullable=true, insertable=true, updatable=true)

	public long getWsAccessRights() {
		return wsAccessRights;
	}

	public void setWsAccessRights(long wsAccessRights) {
		this.wsAccessRights = wsAccessRights;
	}
	@Column(name="ui_access_rights", unique=false, nullable=true, insertable=true, updatable=true)

	public long getUiAccessRights() {
		return uiAccessRights;
	}

	public void setUiAccessRights(long uiAccessRights) {
		this.uiAccessRights = uiAccessRights;
	}
}
