package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.beone.shg.net.config.EnumConst;


/**
 * GInvtAc generated by hbm2java
 */
@Entity
@Table(name="g_invt_ac"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class GInvtAc  implements java.io.Serializable, Comparable<GInvtAc> {

	// Fields    
	private static final long serialVersionUID = -7853284698707508952L;
	private long GInvtAcNo;
	private GAc GAc;
	private long bGroupAcNo;
	private long invtBankAcNo;
	private int investmentTypeId;
	private int accountStatusId;
	private long approvedByMember;
	private String investmentNo;
	private String investmentAcName;
	private String investmentDesc;
	private BigDecimal invtAm;
	private BigDecimal recInvtAm;
	private BigDecimal recInterestAm;
	private BigDecimal projInterestAm;
	private Float interestRate;
	private Date requestedDate;
	private Date approvedDate;
	private Date maturityDate;
	private Date closureDate;
	private String attachmentUrl;
	private String developmentPlan;

	// Constructors

	/** default constructor */
	public GInvtAc() {
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="g_invt_ac_no", unique=true, nullable=false, insertable=true, updatable=true)
	public long getGInvtAcNo() {
		return this.GInvtAcNo;
	}

	public void setGInvtAcNo(long GInvtAcNo) {
		this.GInvtAcNo = GInvtAcNo;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public GAc getGAc() {
		return this.GAc;
	}

	public void setGAc(GAc GAc) {
		this.GAc = GAc;
	}
	@Column(name="b_g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getBGroupAcNo() {
		return this.bGroupAcNo;
	}

	public void setBGroupAcNo(long bGroupAcNo) {
		this.bGroupAcNo = bGroupAcNo;
	}
	@Column(name="invt_bank_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getInvtBankAcNo() {
		return invtBankAcNo;
	}

	public void setInvtBankAcNo(long invtBankAcNo) {
		this.invtBankAcNo = invtBankAcNo;
	}
	@Column(name="investment_type_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getInvestmentTypeId() {
		return this.investmentTypeId;
	}

	public void setInvestmentTypeId(int investmentTypeId) {
		this.investmentTypeId = investmentTypeId;
	}
	@Column(name="account_status_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getAccountStatusId() {
		return this.accountStatusId;
	}

	public void setAccountStatusId(int accountStatusId) {
		this.accountStatusId = accountStatusId;
	}
	@Column(name="approved_by_m", unique=false, nullable=true, insertable=true, updatable=true)

	public long getApprovedByMember() {
		return this.approvedByMember;
	}

	public void setApprovedByMember(long approvedByMember) {
		this.approvedByMember = approvedByMember;
	}
	@Column(name="investment_no", unique=false, nullable=true, insertable=true, updatable=true, length=20)

	public String getInvestmentNo() {
		return investmentNo;
	}

	public void setInvestmentNo(String investmentNo) {
		this.investmentNo = investmentNo;
	}
	@Column(name="investment_ac_name", unique=false, nullable=true, insertable=true, updatable=true, length=50)

	public String getInvestmentAcName() {
		return investmentAcName;
	}

	public void setInvestmentAcName(String investmentAcName) {
		this.investmentAcName = investmentAcName;
	}
	@Column(name="investment_desc", unique=false, nullable=true, insertable=true, updatable=true, length=200)

	public String getInvestmentDesc() {
		return investmentDesc;
	}

	public void setInvestmentDesc(String investmentDesc) {
		this.investmentDesc = investmentDesc;
	}
	@Column(name="invt_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getInvtAm() {
		return this.invtAm;
	}

	public void setInvtAm(BigDecimal invtAm) {
		this.invtAm = invtAm;
	}
	@Column(name="rec_invt_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecInvtAm() {
		return this.recInvtAm;
	}

	public void setRecInvtAm(BigDecimal recInvtAm) {
		this.recInvtAm = recInvtAm;
	}
	@Column(name="rec_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecInterestAm() {
		return this.recInterestAm;
	}

	public void setRecInterestAm(BigDecimal recInterestAm) {
		this.recInterestAm = recInterestAm;
	}
	@Column(name="proj_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjInterestAm() {
		return this.projInterestAm;
	}

	public void setProjInterestAm(BigDecimal projInterestAm) {
		this.projInterestAm = projInterestAm;
	}
	@Column(name="interest_rate", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public Float getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(Float interestRate) {
		this.interestRate = interestRate;
	}
	@Column(name="requested_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}
	@Column(name="approved_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}
	@Column(name="maturity_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(Date maturityDate) {
		this.maturityDate = maturityDate;
	}
	@Column(name="closure_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getClosureDate() {
		return this.closureDate;
	}

	public void setClosureDate(Date closureDate) {
		this.closureDate = closureDate;
	}
	@Column(name="attachment_url", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}
	@Column(name="development_plan", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getDevelopmentPlan() {
		return developmentPlan;
	}

	public void setDevelopmentPlan(String developmentPlan) {
		this.developmentPlan = developmentPlan;
	}

	@Override
	public int compareTo(GInvtAc o) {
		if(o == null) {
			return 1;
		}
		int s1 = EnumConst.getAccountStatusOrder(this.accountStatusId);
		int s2 = EnumConst.getAccountStatusOrder(o.accountStatusId);

		if (s1 < s2) {
			return -1;
		} else if (s1 > s2) {
			return 1;
		} else if (s1 == s2) {
			if (this.GInvtAcNo < o.GInvtAcNo) {
				return -1;
			} else if (this.GInvtAcNo > o.GInvtAcNo) {
				return 1;
			}
		}
		return 0;
	}
}
