package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GM generated by hbm2java
 */
@Entity
@Table(name="g_m"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class GM  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -4289675497583947197L;
	private GMId id;
	private long groupAcNo;
	private long memberAcNo;
	private long wsAccessRights;
	private long uiAccessRights;

	// Constructors

	/** default constructor */
	public GM() {
	}

	/** constructor */
	public GM(long groupAcNo, long memberAcNo) {
		this.groupAcNo = groupAcNo;
		this.memberAcNo = memberAcNo;
	}

	/** full constructor */
	public GM(GMId id, long groupAcNo, long memberAcNo) {
		this.id = id;
		this.groupAcNo = groupAcNo;
		this.memberAcNo = memberAcNo;
	}


	// Property accessors
	@EmbeddedId
	@AttributeOverrides( { 
		@AttributeOverride(name="groupAcNo", column=@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ),
		@AttributeOverride(name="memberAcNo", column=@Column(name="m_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public GMId getId() {
		return this.id;
	}

	public void setId(GMId id) {
		this.id = id;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getGroupAcNo() {
		return this.groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
	@Column(name="m_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getMemberAcNo() {
		return this.memberAcNo;
	}

	public void setMemberAcNo(long memberAcNo) {
		this.memberAcNo = memberAcNo;
	}
	@Column(name="ws_access_rights", unique=false, nullable=true, insertable=true, updatable=true)

	public long getWsAccessRights() {
		return wsAccessRights;
	}

	public void setWsAccessRights(long wsAccessRights) {
		this.wsAccessRights = wsAccessRights;
	}
	@Column(name="ui_access_rights", unique=false, nullable=true, insertable=true, updatable=true)

	public long getUiAccessRights() {
		return uiAccessRights;
	}

	public void setUiAccessRights(long uiAccessRights) {
		this.uiAccessRights = uiAccessRights;
	}
}
