package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * GRules generated by hbm2java
 */
@Entity
@Table(name="g_rules"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class GRules  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 7971581876824618367L;
	private long GAcNo;
	private GProfile GProfile;
	private short maxNoOfCoreMembers;
	private short allowAssociateMembers;
	private int cmMonthlySaving;
	private int amMinMonthlySaving;
	private int amMaxMonthlySaving;
	private short cmRegistrationFee;
	private short amRegistrationFee;
	private short cmSavingLateFee;
	private short amSavingLateFee;
	private short cmLoanLateFee;
	private short amLoanLateFee;
	private short chequeBouncingPenalty;
	private short autoDebitFailurePenalty;
	private short cmApplicationFee;
	private short amApplicationFee;
	private float cmLoanProcessingFeePercent;
	private float amLoanProcessingFeePercent;
	private float cmIntOnSaving;
	private float amIntOnSaving;
	private float cmBaseIntOnLoan;
	private float amBaseIntOnLoan;
	private short addIntToSavingAfterMonths;
	private float intOnConsumptionLoan;
	private int individualDevLoanRange1;
	private int individualDevLoanRange2;
	private int individualDevLoanRange3;
	private float intOnIndividualDevLoanRange1;
	private float intOnIndividualDevLoanRange2;
	private float intOnIndividualDevLoanRange3;
	private float intOnIndividualDevLoanRange4;
	private int projectDevLoanRange1;
	private int projectDevLoanRange2;
	private int projectDevLoanRange3;
	private float intOnProjectDevLoanRange1;
	private float intOnProjectDevLoanRange2;
	private float intOnProjectDevLoanRange3;
	private float intOnProjectDevLoanRange4;
	private float cmSavingXConsumptionLoan;
	private float amSavingXConsumptionLoan;
	private int cmMinMonthsToConLoan;
	private int amMinMonthsToConLoan;
	private int cmLimitOnConsumptionLoan;
	private int amLimitOnConsumptionLoan;
	private float cmSavingXDevLoan;
	private float amSavingXDevLoan;
	private int cmMinMonthsToDevLoan;
	private int amMinMonthsToDevLoan;
	private int cmMinMonthsIntOnLoan;
	private int amMinMonthsIntOnLoan;
	private float creditRatingLoanPassAbove;
	private float creditRatingLoanCausionAbove;
	private float creditRatingLoanDengerousAbove;
	private int computeDayOfMonth;
	private int dueDayOfMonth;
	private long smsSubKey;
	private long mailSubKey;
	private long reportPrintingService;
	private int smsServiceLang;
	private int mailServiceLang;
	private int reportPrintingServiceLang;
	private long activationFlags;
	private short shgOneCMRegCharge;
	private short shgOneAMRegCharge;
	private float shgOneCMLoanProFeePercent;
	private float shgOneAMLoanProFeePercent;
	private short shgOneMinAnnualServiceCharge;
	private short shgOneMaxLoanProFeeOff;
	private int shgOneBillingCycleInMonths;
	private long groupAcNo;

	// Constructors

	/** default constructor */
	public GRules() {
	}

	/** minimal constructor */
	public GRules(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GroupRulesIdGenerator")
	@GenericGenerator(name = "GroupRulesIdGenerator", strategy = "com.beone.shg.net.persistence.generator.GroupRulesIdGenerator")
	@Column(name="g_ac_no", unique=true, nullable=false, insertable=true, updatable=true)

	public long getGAcNo() {
		return this.GAcNo;
	}

	public void setGAcNo(long GAcNo) {
		this.GAcNo = GAcNo;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public GProfile getGProfile() {
		return this.GProfile;
	}

	public void setGProfile(GProfile GProfile) {
		this.GProfile = GProfile;
	}
	@Column(name="max_no_of_core_members", unique=false, nullable=true, insertable=true, updatable=true)

	public short getMaxNoOfCoreMembers() {
		return maxNoOfCoreMembers;
	}

	public void setMaxNoOfCoreMembers(short maxNoOfCoreMembers) {
		this.maxNoOfCoreMembers = maxNoOfCoreMembers;
	}
	@Column(name="allow_associate_members", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAllowAssociateMembers() {
		return allowAssociateMembers;
	}

	public void setAllowAssociateMembers(short allowAssociateMembers) {
		this.allowAssociateMembers = allowAssociateMembers;
	}
	@Column(name="cm_monthly_saving", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCmMonthlySaving() {
		return cmMonthlySaving;
	}

	public void setCmMonthlySaving(int cmMonthlySaving) {
		this.cmMonthlySaving = cmMonthlySaving;
	}
	@Column(name="am_min_monthly_saving", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmMinMonthlySaving() {
		return amMinMonthlySaving;
	}

	public void setAmMinMonthlySaving(int amMinMonthlySaving) {
		this.amMinMonthlySaving = amMinMonthlySaving;
	}
	@Column(name="am_max_monthly_saving", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmMaxMonthlySaving() {
		return amMaxMonthlySaving;
	}

	public void setAmMaxMonthlySaving(int amMaxMonthlySaving) {
		this.amMaxMonthlySaving = amMaxMonthlySaving;
	}
	@Column(name="cm_registration_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getCmRegistrationFee() {
		return this.cmRegistrationFee;
	}

	public void setCmRegistrationFee(short cmRegistrationFee) {
		this.cmRegistrationFee = cmRegistrationFee;
	}
	@Column(name="am_registration_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAmRegistrationFee() {
		return this.amRegistrationFee;
	}

	public void setAmRegistrationFee(short amRegistrationFee) {
		this.amRegistrationFee = amRegistrationFee;
	}
	@Column(name="cm_saving_late_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getCmSavingLateFee() {
		return cmSavingLateFee;
	}

	public void setCmSavingLateFee(short cmSavingLateFee) {
		this.cmSavingLateFee = cmSavingLateFee;
	}
	@Column(name="am_saving_late_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAmSavingLateFee() {
		return amSavingLateFee;
	}

	public void setAmSavingLateFee(short amSavingLateFee) {
		this.amSavingLateFee = amSavingLateFee;
	}
	@Column(name="cm_loan_late_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getCmLoanLateFee() {
		return cmLoanLateFee;
	}

	public void setCmLoanLateFee(short cmLoanLateFee) {
		this.cmLoanLateFee = cmLoanLateFee;
	}
	@Column(name="am_loan_late_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAmLoanLateFee() {
		return amLoanLateFee;
	}

	public void setAmLoanLateFee(short amLoanLateFee) {
		this.amLoanLateFee = amLoanLateFee;
	}

	@Column(name="cheque_bouncing_penalty", unique=false, nullable=true, insertable=true, updatable=true)

	public short getChequeBouncingPenalty() {
		return this.chequeBouncingPenalty;
	}

	public void setChequeBouncingPenalty(short chequeBouncingPenalty) {
		this.chequeBouncingPenalty = chequeBouncingPenalty;
	}
	@Column(name="auto_debit_failure_penalty", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAutoDebitFailurePenalty() {
		return this.autoDebitFailurePenalty;
	}

	public void setAutoDebitFailurePenalty(short autoDebitFailurePenalty) {
		this.autoDebitFailurePenalty = autoDebitFailurePenalty;
	}
	@Column(name="cm_application_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getCmApplicationFee() {
		return cmApplicationFee;
	}

	public void setCmApplicationFee(short cmApplicationFee) {
		this.cmApplicationFee = cmApplicationFee;
	}
	@Column(name="am_application_fee", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAmApplicationFee() {
		return amApplicationFee;
	}

	public void setAmApplicationFee(short amApplicationFee) {
		this.amApplicationFee = amApplicationFee;
	}

	@Column(name="cm_loan_processing_fee_percent", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCmLoanProcessingFeePercent() {
		return this.cmLoanProcessingFeePercent;
	}

	public void setCmLoanProcessingFeePercent(float cmLoanProcessingFeePercent) {
		this.cmLoanProcessingFeePercent = cmLoanProcessingFeePercent;
	}
	@Column(name="am_loan_processing_fee_percent", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getAmLoanProcessingFeePercent() {
		return this.amLoanProcessingFeePercent;
	}

	public void setAmLoanProcessingFeePercent(float amLoanProcessingFeePercent) {
		this.amLoanProcessingFeePercent = amLoanProcessingFeePercent;
	}
	@Column(name="cm_int_on_saving", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCmIntOnSaving() {
		return this.cmIntOnSaving;
	}

	public void setCmIntOnSaving(float cmIntOnSaving) {
		this.cmIntOnSaving = cmIntOnSaving;
	}
	@Column(name="am_int_on_saving", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getAmIntOnSaving() {
		return this.amIntOnSaving;
	}

	public void setAmIntOnSaving(float amIntOnSaving) {
		this.amIntOnSaving = amIntOnSaving;
	}
	@Column(name="cm_base_int_on_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCmBaseIntOnLoan() {
		return this.cmBaseIntOnLoan;
	}

	public void setCmBaseIntOnLoan(float cmBaseIntOnLoan) {
		this.cmBaseIntOnLoan = cmBaseIntOnLoan;
	}
	@Column(name="am_base_int_on_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getAmBaseIntOnLoan() {
		return this.amBaseIntOnLoan;
	}

	public void setAmBaseIntOnLoan(float amBaseIntOnLoan) {
		this.amBaseIntOnLoan = amBaseIntOnLoan;
	}
	@Column(name="add_int_to_saving_after_months", unique=false, nullable=true, insertable=true, updatable=true)

	public short getAddIntToSavingAfterMonths() {
		return this.addIntToSavingAfterMonths;
	}

	public void setAddIntToSavingAfterMonths(short addIntToSavingAfterMonths) {
		this.addIntToSavingAfterMonths = addIntToSavingAfterMonths;
	}
	@Column(name="int_on_consumption_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnConsumptionLoan() {
		return this.intOnConsumptionLoan;
	}

	public void setIntOnConsumptionLoan(float intOnConsumptionLoan) {
		this.intOnConsumptionLoan = intOnConsumptionLoan;
	}
	@Column(name="individual_dev_loan_range1", unique=false, nullable=true, insertable=true, updatable=true)

	public int getIndividualDevLoanRange1() {
		return this.individualDevLoanRange1;
	}

	public void setIndividualDevLoanRange1(int individualDevLoanRange1) {
		this.individualDevLoanRange1 = individualDevLoanRange1;
	}
	@Column(name="individual_dev_loan_range2", unique=false, nullable=true, insertable=true, updatable=true)

	public int getIndividualDevLoanRange2() {
		return this.individualDevLoanRange2;
	}

	public void setIndividualDevLoanRange2(int individualDevLoanRange2) {
		this.individualDevLoanRange2 = individualDevLoanRange2;
	}
	@Column(name="individual_dev_loan_range3", unique=false, nullable=true, insertable=true, updatable=true)

	public int getIndividualDevLoanRange3() {
		return this.individualDevLoanRange3;
	}

	public void setIndividualDevLoanRange3(int individualDevLoanRange3) {
		this.individualDevLoanRange3 = individualDevLoanRange3;
	}
	@Column(name="int_on_individual_dev_loan_range1", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnIndividualDevLoanRange1() {
		return this.intOnIndividualDevLoanRange1;
	}

	public void setIntOnIndividualDevLoanRange1(float intOnIndividualDevLoanRange1) {
		this.intOnIndividualDevLoanRange1 = intOnIndividualDevLoanRange1;
	}
	@Column(name="int_on_individual_dev_loan_range2", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnIndividualDevLoanRange2() {
		return this.intOnIndividualDevLoanRange2;
	}

	public void setIntOnIndividualDevLoanRange2(float intOnIndividualDevLoanRange2) {
		this.intOnIndividualDevLoanRange2 = intOnIndividualDevLoanRange2;
	}
	@Column(name="int_on_individual_dev_loan_range3", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnIndividualDevLoanRange3() {
		return this.intOnIndividualDevLoanRange3;
	}

	public void setIntOnIndividualDevLoanRange3(float intOnIndividualDevLoanRange3) {
		this.intOnIndividualDevLoanRange3 = intOnIndividualDevLoanRange3;
	}
	@Column(name="int_on_individual_dev_loan_range4", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnIndividualDevLoanRange4() {
		return this.intOnIndividualDevLoanRange4;
	}

	public void setIntOnIndividualDevLoanRange4(float intOnIndividualDevLoanRange4) {
		this.intOnIndividualDevLoanRange4 = intOnIndividualDevLoanRange4;
	}
	@Column(name="project_dev_loan_range1", unique=false, nullable=true, insertable=true, updatable=true)

	public int getProjectDevLoanRange1() {
		return this.projectDevLoanRange1;
	}

	public void setProjectDevLoanRange1(int projectDevLoanRange1) {
		this.projectDevLoanRange1 = projectDevLoanRange1;
	}
	@Column(name="project_dev_loan_range2", unique=false, nullable=true, insertable=true, updatable=true)

	public int getProjectDevLoanRange2() {
		return this.projectDevLoanRange2;
	}

	public void setProjectDevLoanRange2(int projectDevLoanRange2) {
		this.projectDevLoanRange2 = projectDevLoanRange2;
	}
	@Column(name="project_dev_loan_range3", unique=false, nullable=true, insertable=true, updatable=true)

	public int getProjectDevLoanRange3() {
		return this.projectDevLoanRange3;
	}

	public void setProjectDevLoanRange3(int projectDevLoanRange3) {
		this.projectDevLoanRange3 = projectDevLoanRange3;
	}
	@Column(name="int_on_project_dev_loan_range1", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnProjectDevLoanRange1() {
		return this.intOnProjectDevLoanRange1;
	}

	public void setIntOnProjectDevLoanRange1(float intOnProjectDevLoanRange1) {
		this.intOnProjectDevLoanRange1 = intOnProjectDevLoanRange1;
	}
	@Column(name="int_on_project_dev_loan_range2", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnProjectDevLoanRange2() {
		return this.intOnProjectDevLoanRange2;
	}

	public void setIntOnProjectDevLoanRange2(float intOnProjectDevLoanRange2) {
		this.intOnProjectDevLoanRange2 = intOnProjectDevLoanRange2;
	}
	@Column(name="int_on_project_dev_loan_range3", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnProjectDevLoanRange3() {
		return this.intOnProjectDevLoanRange3;
	}

	public void setIntOnProjectDevLoanRange3(float intOnProjectDevLoanRange3) {
		this.intOnProjectDevLoanRange3 = intOnProjectDevLoanRange3;
	}
	@Column(name="int_on_project_dev_loan_range4", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getIntOnProjectDevLoanRange4() {
		return this.intOnProjectDevLoanRange4;
	}

	public void setIntOnProjectDevLoanRange4(float intOnProjectDevLoanRange4) {
		this.intOnProjectDevLoanRange4 = intOnProjectDevLoanRange4;
	}
	@Column(name="cm_saving_x_consumption_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCmSavingXConsumptionLoan() {
		return this.cmSavingXConsumptionLoan;
	}

	public void setCmSavingXConsumptionLoan(float cmSavingXConsumptionLoan) {
		this.cmSavingXConsumptionLoan = cmSavingXConsumptionLoan;
	}
	@Column(name="am_saving_x_consumption_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getAmSavingXConsumptionLoan() {
		return this.amSavingXConsumptionLoan;
	}

	public void setAmSavingXConsumptionLoan(float amSavingXConsumptionLoan) {
		this.amSavingXConsumptionLoan = amSavingXConsumptionLoan;
	}
	@Column(name="cm_min_months_to_con_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCmMinMonthsToConLoan() {
		return cmMinMonthsToConLoan;
	}

	public void setCmMinMonthsToConLoan(int cmMinMonthsToConLoan) {
		this.cmMinMonthsToConLoan = cmMinMonthsToConLoan;
	}
	@Column(name="am_min_months_to_con_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmMinMonthsToConLoan() {
		return amMinMonthsToConLoan;
	}

	public void setAmMinMonthsToConLoan(int amMinMonthsToConLoan) {
		this.amMinMonthsToConLoan = amMinMonthsToConLoan;
	}

	@Column(name="cm_limit_on_consumption_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCmLimitOnConsumptionLoan() {
		return this.cmLimitOnConsumptionLoan;
	}

	public void setCmLimitOnConsumptionLoan(int cmLimitOnConsumptionLoan) {
		this.cmLimitOnConsumptionLoan = cmLimitOnConsumptionLoan;
	}
	@Column(name="am_limit_on_consumption_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmLimitOnConsumptionLoan() {
		return this.amLimitOnConsumptionLoan;
	}

	public void setAmLimitOnConsumptionLoan(int amLimitOnConsumptionLoan) {
		this.amLimitOnConsumptionLoan = amLimitOnConsumptionLoan;
	}
	@Column(name="cm_saving_x_dev_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCmSavingXDevLoan() {
		return this.cmSavingXDevLoan;
	}

	public void setCmSavingXDevLoan(float cmSavingXDevLoan) {
		this.cmSavingXDevLoan = cmSavingXDevLoan;
	}
	@Column(name="am_saving_x_dev_loan", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getAmSavingXDevLoan() {
		return this.amSavingXDevLoan;
	}

	public void setAmSavingXDevLoan(float amSavingXDevLoan) {
		this.amSavingXDevLoan = amSavingXDevLoan;
	}
	@Column(name="cm_min_months_to_dev_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCmMinMonthsToDevLoan() {
		return cmMinMonthsToDevLoan;
	}

	public void setCmMinMonthsToDevLoan(int cmMinMonthsToDevLoan) {
		this.cmMinMonthsToDevLoan = cmMinMonthsToDevLoan;
	}
	@Column(name="am_min_months_to_dev_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmMinMonthsToDevLoan() {
		return amMinMonthsToDevLoan;
	}

	public void setAmMinMonthsToDevLoan(int amMinMonthsToDevLoan) {
		this.amMinMonthsToDevLoan = amMinMonthsToDevLoan;
	}
	@Column(name="cm_min_months_int_on_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getCmMinMonthsIntOnLoan() {
		return cmMinMonthsIntOnLoan;
	}

	public void setCmMinMonthsIntOnLoan(int cmMinMonthsIntOnLoan) {
		this.cmMinMonthsIntOnLoan = cmMinMonthsIntOnLoan;
	}
	@Column(name="am_min_months_int_on_loan", unique=false, nullable=true, insertable=true, updatable=true)

	public int getAmMinMonthsIntOnLoan() {
		return amMinMonthsIntOnLoan;
	}

	public void setAmMinMonthsIntOnLoan(int amMinMonthsIntOnLoan) {
		this.amMinMonthsIntOnLoan = amMinMonthsIntOnLoan;
	}

	@Column(name="credit_rating_loan_pass_above", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCreditRatingLoanPassAbove() {
		return this.creditRatingLoanPassAbove;
	}

	public void setCreditRatingLoanPassAbove(float creditRatingLoanPassAbove) {
		this.creditRatingLoanPassAbove = creditRatingLoanPassAbove;
	}
	@Column(name="credit_rating_loan_causion_above", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCreditRatingLoanCausionAbove() {
		return this.creditRatingLoanCausionAbove;
	}

	public void setCreditRatingLoanCausionAbove(float creditRatingLoanCausionAbove) {
		this.creditRatingLoanCausionAbove = creditRatingLoanCausionAbove;
	}
	@Column(name="credit_rating_loan_dengerous_above", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getCreditRatingLoanDengerousAbove() {
		return this.creditRatingLoanDengerousAbove;
	}

	public void setCreditRatingLoanDengerousAbove(float creditRatingLoanDengerousAbove) {
		this.creditRatingLoanDengerousAbove = creditRatingLoanDengerousAbove;
	}
	@Column(name="compute_day_of_month", unique=false, nullable=true, insertable=true, updatable=true)

	public int getComputeDayOfMonth() {
		return this.computeDayOfMonth;
	}

	public void setComputeDayOfMonth(int computeDayOfMonth) {
		this.computeDayOfMonth = computeDayOfMonth;
	}
	@Column(name="due_day_of_month", unique=false, nullable=true, insertable=true, updatable=true)

	public int getDueDayOfMonth() {
		return this.dueDayOfMonth;
	}

	public void setDueDayOfMonth(int dueDayOfMonth) {
		this.dueDayOfMonth = dueDayOfMonth;
	}
	@Column(name="sms_sub_key", unique=false, nullable=true, insertable=true, updatable=true)

	public long getSmsSubKey() {
		return smsSubKey;
	}

	public void setSmsSubKey(long smsSubKey) {
		this.smsSubKey = smsSubKey;
	}
	@Column(name="mail_sub_key", unique=false, nullable=true, insertable=true, updatable=true)

	public long getMailSubKey() {
		return mailSubKey;
	}

	public void setMailSubKey(long mailSubKey) {
		this.mailSubKey = mailSubKey;
	}

	@Column(name="report_printing_service", unique=false, nullable=true, insertable=true, updatable=true)

	public long getReportPrintingService() {
		return reportPrintingService;
	}

	public void setReportPrintingService(long reportPrintingService) {
		this.reportPrintingService = reportPrintingService;
	}
	@Column(name="sms_service_lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getSmsServiceLang() {
		return smsServiceLang;
	}

	public void setSmsServiceLang(int smsServiceLang) {
		this.smsServiceLang = smsServiceLang;
	}
	@Column(name="mail_service_lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getMailServiceLang() {
		return mailServiceLang;
	}

	public void setMailServiceLang(int mailServiceLang) {
		this.mailServiceLang = mailServiceLang;
	}
	@Column(name="report_printing_service_lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getReportPrintingServiceLang() {
		return reportPrintingServiceLang;
	}

	public void setReportPrintingServiceLang(int reportPrintingServiceLang) {
		this.reportPrintingServiceLang = reportPrintingServiceLang;
	}
	@Column(name="activation_flags", unique=false, nullable=true, insertable=true, updatable=true)

	public long getActivationFlags() {
		return activationFlags;
	}

	public void setActivationFlags(long activationFlags) {
		this.activationFlags = activationFlags;
	}

	@Column(name="shg_one_cm_reg_charge", unique=false, nullable=true, insertable=true, updatable=true)

	public short getShgOneCMRegCharge() {
		return shgOneCMRegCharge;
	}

	public void setShgOneCMRegCharge(short shgOneCMRegCharge) {
		this.shgOneCMRegCharge = shgOneCMRegCharge;
	}
	@Column(name="shg_one_am_reg_charge", unique=false, nullable=true, insertable=true, updatable=true)

	public short getShgOneAMRegCharge() {
		return shgOneAMRegCharge;
	}

	public void setShgOneAMRegCharge(short shgOneAMRegCharge) {
		this.shgOneAMRegCharge = shgOneAMRegCharge;
	}
	@Column(name="shg_one_cm_loan_pro_fee_percent", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getShgOneCMLoanProFeePercent() {
		return shgOneCMLoanProFeePercent;
	}

	public void setShgOneCMLoanProFeePercent(float shgOneCMLoanProFeePercent) {
		this.shgOneCMLoanProFeePercent = shgOneCMLoanProFeePercent;
	}
	@Column(name="shg_one_am_loan_pro_fee_percent", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

	public float getShgOneAMLoanProFeePercent() {
		return shgOneAMLoanProFeePercent;
	}

	public void setShgOneAMLoanProFeePercent(float shgOneAMLoanProFeePercent) {
		this.shgOneAMLoanProFeePercent = shgOneAMLoanProFeePercent;
	}
	@Column(name="shg_one_min_annual_service_charge", unique=false, nullable=true, insertable=true, updatable=true)

	public short getShgOneMinAnnualServiceCharge() {
		return shgOneMinAnnualServiceCharge;
	}

	public void setShgOneMinAnnualServiceCharge(
			short shgOneMinAnnualServiceCharge) {
		this.shgOneMinAnnualServiceCharge = shgOneMinAnnualServiceCharge;
	}
	@Column(name="shg_one_max_loan_pro_fee_off", unique=false, nullable=true, insertable=true, updatable=true)

	public short getShgOneMaxLoanProFeeOff() {
		return shgOneMaxLoanProFeeOff;
	}

	public void setShgOneMaxLoanProFeeOff(short shgOneMaxLoanProFeeOff) {
		this.shgOneMaxLoanProFeeOff = shgOneMaxLoanProFeeOff;
	}
	@Column(name="shg_one_billing_cycle_in_months", unique=false, nullable=true, insertable=true, updatable=true)

	public int getShgOneBillingCycleInMonths() {
		return shgOneBillingCycleInMonths;
	}

	public void setShgOneBillingCycleInMonths(int shgOneBillingCycleInMonths) {
		this.shgOneBillingCycleInMonths = shgOneBillingCycleInMonths;
	}

	@Transient
	public long getGroupAcNo() {
		return groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
}
