package com.beone.shg.net.persistence.model;
// Generated Mar 25, 2014 10:30:57 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * InvestmentType generated by hbm2java
 */
@Entity
@Table(name="investment_type"
,catalog="shg"
//, uniqueConstraints = {  }
		)

public class InvestmentType  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -7748181820058346375L;
	private int investmentTypeId;
	private String investmentType;
	private String investmentTypeDesc;

	// Constructors

	/** default constructor */
	public InvestmentType() {
	}

	/** minimal constructor */
	public InvestmentType(int investmentTypeId, String investmentType) {
		this.investmentTypeId = investmentTypeId;
		this.investmentType = investmentType;
	}

	/** minimal constructor */
	public InvestmentType(String investmentType, String investmentTypeDesc) {
		this.investmentType = investmentType;
		this.investmentTypeDesc = investmentTypeDesc;
	}

	/** full constructor */
	public InvestmentType(int investmentTypeId, String investmentType, String investmentTypeDesc) {
		this.investmentTypeId = investmentTypeId;
		this.investmentType = investmentType;
		this.investmentTypeDesc = investmentTypeDesc;
	} 

	// Property accessors
	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="investment_type_id", unique=true, nullable=false, insertable=true, updatable=true)
	public int getInvestmentTypeId() {
		return this.investmentTypeId;
	}

	public void setInvestmentTypeId(int investmentTypeId) {
		this.investmentTypeId = investmentTypeId;
	}
	@Column(name="investment_type", unique=false, nullable=false, insertable=true, updatable=true, length=30)

	public String getInvestmentType() {
		return this.investmentType;
	}

	public void setInvestmentType(String investmentType) {
		this.investmentType = investmentType;
	}
	@Column(name="investment_type_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getInvestmentTypeDesc() {
		return this.investmentTypeDesc;
	}

	public void setInvestmentTypeDesc(String investmentTypeDesc) {
		this.investmentTypeDesc = investmentTypeDesc;
	}
}
