package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LanguageMassage generated by hbm2java
 */
@Entity
@Table(name="language_massage"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class LanguageMassage  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 1213586440943825567L;
	private LanguageMassageId id;
	private Lang lang;
	private String massageKey;
	private String massage;
	private String massageDesc;

	// Constructors

	/** default constructor */
	public LanguageMassage() {
	}

	/** minimal constructor */
	public LanguageMassage(LanguageMassageId id, Lang lang) {
		this.id = id;
		this.lang = lang;
	}

	/** full constructor */
	public LanguageMassage(LanguageMassageId id, Lang lang, String massageKey, String massage, String massageDesc) {
		this.id = id;
		this.lang = lang;
		this.massageKey = massageKey;
		this.massage = massage;
		this.massageDesc = massageDesc;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="massageId", column=@Column(name="massage_id", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="langId", column=@Column(name="lang_id", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public LanguageMassageId getId() {
		return this.id;
	}

	public void setId(LanguageMassageId id) {
		this.id = id;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="lang_id", unique=false, nullable=false, insertable=false, updatable=false)

	public Lang getLang() {
		return this.lang;
	}

	public void setLang(Lang lang) {
		this.lang = lang;
	}
	@Column(name="massage_key", unique=false, nullable=true, insertable=true, updatable=true, length=45)

	public String getMassageKey() {
		return this.massageKey;
	}

	public void setMassageKey(String massageKey) {
		this.massageKey = massageKey;
	}
	@Column(name="massage", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getMassage() {
		return this.massage;
	}

	public void setMassage(String massage) {
		this.massage = massage;
	}
	@Column(name="massage_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getMassageDesc() {
		return this.massageDesc;
	}

	public void setMassageDesc(String massageDesc) {
		this.massageDesc = massageDesc;
	}
}
