package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:17 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Lang generated by hbm2java
 */
@Entity
@Table(name="lang"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class Lang  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 7487974946912289684L;
	private int langId;
	private String lang;
	private String langDesc;

	// Constructors

	/** default constructor */
	public Lang() {
	}

	/** minimal constructor */
	public Lang(String lang, String langDesc) {
		this.lang = lang;
		this.langDesc = langDesc;
	}

	/** full constructor */
	public Lang(int langId, String lang, String langDesc) {
		this.langId = langId;
		this.lang = lang;
		this.langDesc = langDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="lang_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getLangId() {
		return this.langId;
	}

	public void setLangId(int langId) {
		this.langId = langId;
	}
	@Column(name="lang", unique=false, nullable=false, insertable=true, updatable=true, length=15)

	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}
	@Column(name="lang_desc", unique=false, nullable=false, insertable=true, updatable=true, length=100)

	public String getLangDesc() {
		return this.langDesc;
	}

	public void setLangDesc(String langDesc) {
		this.langDesc = langDesc;
	}

}
