package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LanguageMassageId generated by hbm2java
 */
@Embeddable

public class LanguageMassageId  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -6393742645251738734L;
	private int massageId;
	private int langId;

	// Constructors

	/** default constructor */
	public LanguageMassageId() {
	}

	/** full constructor */
	public LanguageMassageId(int massageId, int langId) {
		this.massageId = massageId;
		this.langId = langId;
	}

	// Property accessors
	@Column(name="massage_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getMassageId() {
		return this.massageId;
	}

	public void setMassageId(int massageId) {
		this.massageId = massageId;
	}
	@Column(name="lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getLangId() {
		return this.langId;
	}

	public void setLangId(int langId) {
		this.langId = langId;
	}

	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof LanguageMassageId) ) return false;
		LanguageMassageId castOther = ( LanguageMassageId ) other; 

		return (this.getMassageId()==castOther.getMassageId())
				&& (this.getLangId()==castOther.getLangId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMassageId();
		result = 37 * result + this.getLangId();
		return result;
	}   
}
