package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * LoanSource generated by hbm2java
 */
@Entity
@Table(name="loan_source"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class LoanSource  implements java.io.Serializable {

	private static final long serialVersionUID = 5238537849676327349L;
	private int loanSourceId;
	private String loanSource;
	private String loanSourceDesc;


	// Constructors

	/** default constructor */
	public LoanSource() {
	}

	/** minimal constructor */
	public LoanSource(String loanSource, String loanSourceDesc) {
		this.loanSource = loanSource;
		this.loanSourceDesc = loanSourceDesc;
	}

	/** full constructor */
	public LoanSource(int loanSourceId, String loanSource, String loanSourceDesc) {
		this.loanSourceId = loanSourceId;
		this.loanSource = loanSource;
		this.loanSourceDesc = loanSourceDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="loan_source_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getLoanSourceId() {
		return this.loanSourceId;
	}

	public void setLoanSourceId(int loanSourceId) {
		this.loanSourceId = loanSourceId;
	}
	@Column(name="loan_source", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getLoanSource() {
		return this.loanSource;
	}

	public void setLoanSource(String loanSource) {
		this.loanSource = loanSource;
	}
	@Column(name="loan_source_desc", unique=false, nullable=false, insertable=true, updatable=true, length=100)

	public String getLoanSourceDesc() {
		return this.loanSourceDesc;
	}

	public void setLoanSourceDesc(String loanSourceDesc) {
		this.loanSourceDesc = loanSourceDesc;
	}

}
