package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * MBankAccount generated by hbm2java
 */
@Entity
@Table(name="m_bank_account"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MBankAccount  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -3007605520676549435L;
	private long bankAccountNo;
	private MProfile MProfile;
	private BankAccount bankAccount;

	// Constructors

	/** default constructor */
	public MBankAccount() {
	}

	/** full constructor */
	public MBankAccount(long bankAccountNo, MProfile MProfile, BankAccount bankAccount) {
		this.bankAccountNo = bankAccountNo;
		this.MProfile = MProfile;
		this.bankAccount = bankAccount;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "MBankAccountIdGenerator")
	@GenericGenerator(name = "MBankAccountIdGenerator", strategy = "com.beone.shg.net.persistence.generator.MBankAccountIdGenerator")
	@Column(name="bank_account_no", unique=true, nullable=false, insertable=true, updatable=true)
	public long getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(long bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="m_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public MProfile getMProfile() {
		return this.MProfile;
	}

	public void setMProfile(MProfile MProfile) {
		this.MProfile = MProfile;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="bank_account_no", unique=true, nullable=false, insertable=false, updatable=false)

	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}

}
