package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GAcByTxtype generated by hbm2java
 */
@Entity
@Table(name="monthly_g_ac_by_txtype"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MonthlyGAcByTxtype  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 6315940176107212531L;
	private MonthlyGAcByTxtypeId id;
	private long GAcNo;
	private int txTypeId;
	private String month;
	private BigDecimal amount;

	// Constructors

	/** default constructor */
	public MonthlyGAcByTxtype() {
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="GAcNo", column=@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="txTypeId", column=@Column(name="tx_type_id", unique=false, nullable=false, insertable=true, updatable=true) ),
		@AttributeOverride(name="month", column=@Column(name="month", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public MonthlyGAcByTxtypeId getId() {
		return this.id;
	}

	public void setId(MonthlyGAcByTxtypeId id) {
		this.id = id;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getGAcNo() {
		return this.GAcNo;
	}

	public void setGAcNo(long GAcNo) {
		this.GAcNo = GAcNo;
	}
	@Column(name="tx_type_id", unique=false, nullable=false, insertable=false, updatable=false)

	public int getTxTypeId() {
		return this.txTypeId;
	}

	public void setTxTypeId(int txTypeId) {
		this.txTypeId = txTypeId;
	}

	@Column(name="month", unique=false, nullable=false, insertable=false, updatable=false, length=10)
	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name="amount", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}   
}
