package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * GInvtAc generated by hbm2java
 */
@Entity
@Table(name="monthly_g_invt_ac"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MonthlyGInvtAc  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -7853284698707508952L;
	private MonthlyGInvtAcId id;
	private long GInvtAcNo;
	private String month;
	private long groupAcNo;
	private long bGroupAcNo;
	private int investmentTypeId;
	private int accountStatus;
	private String investmentAcName;
	private BigDecimal invtAm;
	private BigDecimal recInvtAm;
	private BigDecimal recInterestAm;
	private BigDecimal projInterestAm;

	// Constructors

	/** default constructor */
	public MonthlyGInvtAc() {
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="GInvtAcNo", column=@Column(name="g_invt_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="month", column=@Column(name="month", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public MonthlyGInvtAcId getId() {
		return this.id;
	}

	public void setId(MonthlyGInvtAcId id) {
		this.id = id;
	}
	@Column(name="g_invt_ac_no", unique=false, nullable=false, insertable=false, updatable=false)
	public long getGInvtAcNo() {
		return this.GInvtAcNo;
	}

	public void setGInvtAcNo(long GInvtAcNo) {
		this.GInvtAcNo = GInvtAcNo;
	}

	@Column(name="month", unique=false, nullable=false, insertable=false, updatable=false, length=10)
	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getGroupAcNo() {
		return this.groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
	@Column(name="b_group_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getBGroupAcNo() {
		return this.bGroupAcNo;
	}

	public void setBGroupAcNo(long bGroupAcNo) {
		this.bGroupAcNo = bGroupAcNo;
	}
	@Column(name="investment_type_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getInvestmentTypeId() {
		return this.investmentTypeId;
	}

	public void setInvestmentTypeId(int investmentTypeId) {
		this.investmentTypeId = investmentTypeId;
	}
	@Column(name="account_status_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(int accountStatus) {
		this.accountStatus = accountStatus;
	}
	@Column(name="investment_ac_name", unique=false, nullable=true, insertable=true, updatable=true, length=50)

	public String getInvestmentAcName() {
		return investmentAcName;
	}

	public void setInvestmentAcName(String investmentAcName) {
		this.investmentAcName = investmentAcName;
	}
	@Column(name="invt_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getInvtAm() {
		return this.invtAm;
	}

	public void setInvtAm(BigDecimal invtAm) {
		this.invtAm = invtAm;
	}
	@Column(name="rec_invt_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecInvtAm() {
		return this.recInvtAm;
	}

	public void setRecInvtAm(BigDecimal recInvtAm) {
		this.recInvtAm = recInvtAm;
	}
	@Column(name="rec_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getRecInterestAm() {
		return this.recInterestAm;
	}

	public void setRecInterestAm(BigDecimal recInterestAm) {
		this.recInterestAm = recInterestAm;
	}
	@Column(name="proj_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjInterestAm() {
		return this.projInterestAm;
	}

	public void setProjInterestAm(BigDecimal projInterestAm) {
		this.projInterestAm = projInterestAm;
	}
}
