package com.beone.shg.net.persistence.model;
// Generated Apr 20, 2014 5:26:17 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MonthlyReportItem generated by hbm2java
 */
@Entity
@Table(name="monthly_report_sheet"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MonthlyReportSheet  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -5916347882701484397L;
	private int monthlyReportSheetId;
	private String reportSheetName;
	private String reportSheetTopTitle;
	private String reportSheetBottomTitle;
	private String sheetFormat;
	private String reportSheetDesc;
	private String reportSheetFormula;
	private MonthlyReport monthlyReport;

	// Constructors

	/** default constructor */
	public MonthlyReportSheet() {
	}

	/** full constructor */
	public MonthlyReportSheet(String reportSheetName, 
			String reportSheetTopTitle,
			String reportSheetBottomTitle,
			String sheetFormat,
			String reportSheetDesc,
			String reportSheetFormula, 
			MonthlyReport monthlyReport) {
		super();
		this.reportSheetName = reportSheetName;
		this.reportSheetTopTitle = reportSheetTopTitle;
		this.reportSheetBottomTitle = reportSheetBottomTitle;
		this.sheetFormat = sheetFormat;
		this.reportSheetDesc = reportSheetDesc;
		this.reportSheetFormula = reportSheetFormula;
		this.monthlyReport = monthlyReport;
	}

	/** full constructor */
	public MonthlyReportSheet(int monthlyReportSheetId, 
			String reportSheetName, 
			String reportSheetTopTitle,
			String reportSheetBottomTitle,
			String sheetFormat, 
			String reportSheetDesc,
			String reportSheetFormula, 
			MonthlyReport monthlyReport) {
		super();
		this.monthlyReportSheetId = monthlyReportSheetId;
		this.reportSheetName = reportSheetName;
		this.reportSheetTopTitle = reportSheetTopTitle;
		this.reportSheetBottomTitle = reportSheetBottomTitle;
		this.sheetFormat = sheetFormat;
		this.reportSheetDesc = reportSheetDesc;
		this.reportSheetFormula = reportSheetFormula;
		this.monthlyReport = monthlyReport;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="monthly_report_sheet_id", unique=true, nullable=false, insertable=true, updatable=true)
	public int getMonthlyReportSheetId() {
		return monthlyReportSheetId;
	}

	public void setMonthlyReportSheetId(int monthlyReportSheetId) {
		this.monthlyReportSheetId = monthlyReportSheetId;
	}

	@Column(name="report_sheet_name", unique=false, nullable=true, insertable=true, updatable=true, length=50)
	public String getReportSheetName() {
		return reportSheetName;
	}

	public void setReportSheetName(String reportSheetName) {
		this.reportSheetName = reportSheetName;
	}

	@Column(name="report_sheet_top_title", unique=false, nullable=true, insertable=true, updatable=true, length=50)
	public String getReportSheetTopTitle() {
		return reportSheetTopTitle;
	}

	public void setReportSheetTopTitle(String reportSheetTopTitle) {
		this.reportSheetTopTitle = reportSheetTopTitle;
	}

	@Column(name="report_sheet_bottom_title", unique=false, nullable=true, insertable=true, updatable=true, length=50)
	public String getReportSheetBottomTitle() {
		return reportSheetBottomTitle;
	}

	public void setReportSheetBottomTitle(String reportSheetBottomTitle) {
		this.reportSheetBottomTitle = reportSheetBottomTitle;
	}

	@Column(name="sheet_format", unique=false, nullable=true, insertable=true, updatable=true, length=25)
	public String getSheetFormat() {
		return sheetFormat;
	}

	public void setSheetFormat(String sheetFormat) {
		this.sheetFormat = sheetFormat;
	}

	@Column(name="report_sheet_desc", unique=false, nullable=true, insertable=true, updatable=true, length=200)
	public String getReportSheetDesc() {
		return reportSheetDesc;
	}

	public void setReportSheetDesc(String reportSheetDesc) {
		this.reportSheetDesc = reportSheetDesc;
	}

	@Column(name="report_sheet_formula", unique=false, nullable=true, insertable=true, updatable=true, length=2000)
	public String getReportSheetFormula() {
		return reportSheetFormula;
	}

	public void setReportSheetFormula(String reportSheetFormula) {
		this.reportSheetFormula = reportSheetFormula;
	}

	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="monthly_report_id", unique=false, nullable=false, insertable=true, updatable=true)
	public MonthlyReport getMonthlyReport() {
		return monthlyReport;
	}

	public void setMonthlyReport(MonthlyReport monthlyReport) {
		this.monthlyReport = monthlyReport;
	}

	@Override
	public int hashCode() {
		int hashCode = 37;
		hashCode += (monthlyReportSheetId * 17);
		return hashCode;
	}

	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		return (monthlyReportSheetId == ((MonthlyReportSheet)obj).monthlyReportSheetId);
	}
}
