package com.beone.shg.net.persistence.model;
// Generated Apr 20, 2014 5:26:17 PM by Hibernate Tools 3.1.0.beta4

import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MonthlyReport generated by hbm2java
 */
@Entity
@Table(name="monthly_report"
    ,catalog="shg"
, uniqueConstraints = {  }
)

public class MonthlyReport  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 3878952731744363863L;
     private int monthlyReportId;
     private String reportName;
     private String reportDisplayName;
     private String reportDesc;
     private Set<MonthlyReportSheet> monthlyReportSheets = new LinkedHashSet<MonthlyReportSheet>(0);

    // Constructors

    /** default constructor */
    public MonthlyReport() {
    }
    
    /** full constructor */
    public MonthlyReport(String reportName, String reportDisplayName, String reportDesc) {
        this.reportName = reportName;
        this.reportDisplayName = reportDisplayName;
        this.reportDesc = reportDesc;
    }
    
    /** full constructor */
    public MonthlyReport(int monthlyReportId, String reportName, String reportDisplayName, String reportDesc) {
        this.monthlyReportId = monthlyReportId;
        this.reportName = reportName;
        this.reportDisplayName = reportDisplayName;
        this.reportDesc = reportDesc;
    }
    
    // Property accessors
    @Id
	@GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="monthly_report_id", unique=true, nullable=false, insertable=true, updatable=true)

    public int getMonthlyReportId() {
        return this.monthlyReportId;
    }
    
    public void setMonthlyReportId(int monthlyReportId) {
        this.monthlyReportId = monthlyReportId;
    }
    @Column(name="report_name", unique=false, nullable=true, insertable=true, updatable=true, length=30)

    public String getReportName() {
        return this.reportName;
    }
    
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
    @Column(name="report_display_name", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getReportDisplayName() {
		return reportDisplayName;
	}

	public void setReportDisplayName(String reportDisplayName) {
		this.reportDisplayName = reportDisplayName;
	}
	@Column(name="report_desc", unique=false, nullable=true, insertable=true, updatable=true, length=200)

    public String getReportDesc() {
        return this.reportDesc;
    }
    
    public void setReportDesc(String reportDesc) {
        this.reportDesc = reportDesc;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="monthlyReport")

    public Set<MonthlyReportSheet> getReportItemMappings() {
        return this.monthlyReportSheets;
    }
    
    public void setReportItemMappings(Set<MonthlyReportSheet> monthlyReportSheets) {
        this.monthlyReportSheets = monthlyReportSheets;
    }
 }
