package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GLoanAc generated by hbm2java
 */
@Entity
@Table(name="monthly_g_loan_ac"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MonthlyGLoanAc  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 4667090026444587197L;
	private MonthlyGLoanAcId id;
	private long GLoanAcNo;
	private String month;
	private long groupAcNo;
	private long bGroupAcNo;
	private int fundTypeId;
	private int accountStatusId;
	private int loanSourceId;
	private String loanAcName;
	private BigDecimal principleAm;
	private BigDecimal pendingPrincipleAm;
	private BigDecimal paidInterestAm;
	private BigDecimal projInterestAm;
	private BigDecimal installmentAm;
	private BigDecimal preEmiInterestAm;
	private BigDecimal pendingInterestDueAm;

	// Constructors

	/** default constructor */
	public MonthlyGLoanAc() {
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name="GLoanAcNo", column=@Column(name="g_loan_ac_no", unique=false, nullable=false, insertable=true, updatable=true) ), 
		@AttributeOverride(name="month", column=@Column(name="month", unique=false, nullable=false, insertable=true, updatable=true) ) } )

	public MonthlyGLoanAcId getId() {
		return this.id;
	}

	public void setId(MonthlyGLoanAcId id) {
		this.id = id;
	}

	@Column(name="month", unique=false, nullable=false, insertable=false, updatable=false, length=10)
	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name="g_loan_ac_no", unique=false, nullable=false, insertable=false, updatable=false)

	public long getGLoanAcNo() {
		return this.GLoanAcNo;
	}

	public void setGLoanAcNo(long GLoanAcNo) {
		this.GLoanAcNo = GLoanAcNo;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getGroupAcNo() {
		return this.groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
	@Column(name="b_group_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getBGroupAcNo() {
		return this.bGroupAcNo;
	}

	public void setBGroupAcNo(long bGroupAcNo) {
		this.bGroupAcNo = bGroupAcNo;
	}
	@Column(name="account_status_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getAccountStatusId() {
		return this.accountStatusId;
	}

	public void setAccountStatusId(int accountStatusId) {
		this.accountStatusId = accountStatusId;
	}
	@Column(name="loan_source_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getLoanSourceId() {
		return this.loanSourceId;
	}

	public void setLoanSourceId(int loanSourceId) {
		this.loanSourceId = loanSourceId;
	}
	@Column(name="loan_ac_name", unique=false, nullable=true, insertable=true, updatable=true, length=50)

	public String getLoanAcName() {
		return loanAcName;
	}

	public void setLoanAcName(String loanAcName) {
		this.loanAcName = loanAcName;
	}
	@Column(name="fund_type_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getFundTypeId() {
		return this.fundTypeId;
	}

	public void setFundTypeId(int fundTypeId) {
		this.fundTypeId = fundTypeId;
	}
	@Column(name="principle_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPrincipleAm() {
		return this.principleAm;
	}

	public void setPrincipleAm(BigDecimal principleAm) {
		this.principleAm = principleAm;
	}
	@Column(name="pending_principle_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPendingPrincipleAm() {
		return this.pendingPrincipleAm;
	}

	public void setPendingPrincipleAm(BigDecimal pendingPrincipleAm) {
		this.pendingPrincipleAm = pendingPrincipleAm;
	}
	@Column(name="paid_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPaidInterestAm() {
		return this.paidInterestAm;
	}

	public void setPaidInterestAm(BigDecimal paidInterestAm) {
		this.paidInterestAm = paidInterestAm;
	}
	@Column(name="proj_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getProjInterestAm() {
		return this.projInterestAm;
	}

	public void setProjInterestAm(BigDecimal projInterestAm) {
		this.projInterestAm = projInterestAm;
	}
	@Column(name="installment_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getInstallmentAm() {
		return this.installmentAm;
	}

	public void setInstallmentAm(BigDecimal installmentAm) {
		this.installmentAm = installmentAm;
	}
	@Column(name="pre_emi_interest_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPreEmiInterestAm() {
		return this.preEmiInterestAm;
	}

	public void setPreEmiInterestAm(BigDecimal preEmiInterestAm) {
		this.preEmiInterestAm = preEmiInterestAm;
	}
	@Column(name="pending_interest_due_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPendingInterestDueAm() {
		return this.pendingInterestDueAm;
	}

	public void setPendingInterestDueAm(BigDecimal pendingInterestDueAm) {
		this.pendingInterestDueAm = pendingInterestDueAm;
	}
}
