package com.beone.shg.net.persistence.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MProfile generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="m_profiling_type"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MProfilingType implements java.io.Serializable {

	private int pointId;
	private String point;
	private String profileFor;
	private String category;
	private String valueType;
	private String options;
	
	public MProfilingType() {
	}
	public MProfilingType(String point, String profileFor, String category, String valueType,
			String options) {
		super();
		this.point = point;
		this.profileFor = profileFor;
		this.category = category;
		this.valueType = valueType;
		this.options = options;
	}
	public MProfilingType(int pointId, String point, String profileFor, String category,
			String valueType, String options) {
		super();
		this.pointId = pointId;
		this.point = point;
		this.profileFor = profileFor;
		this.category = category;
		this.valueType = valueType;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="point_id", unique=true, nullable=false, insertable=true, updatable=true)
	public int getPointId() {
		return pointId;
	}
	public void setPointId(int pointId) {
		this.pointId = pointId;
	}

	@Column(name="point", unique=false, nullable=false, insertable=true, updatable=true, length=45)
	public String getPoint() {
		return point;
	}
	public void setPoint(String point) {
		this.point = point;
	}

	@Column(name="profile_for", unique=false, nullable=false, insertable=true, updatable=true, length=25)
	public String getProfileFor() {
		return profileFor;
	}
	public void setProfileFor(String profileFor) {
		this.profileFor = profileFor;
	}
	
	@Column(name="category", unique=false, nullable=true, insertable=true, updatable=true, length=45)
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name="value_type", unique=false, nullable=false, insertable=true, updatable=true, length=25)
	public String getValueType() {
		return valueType;
	}
	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	@Column(name="options", unique=false, nullable=true, insertable=true, updatable=true, length=1000)
	public String getOptions() {
		return options;
	}
	public void setOptions(String options) {
		this.options = options;
	}
}
