package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MSavingAc generated by hbm2java
 */
@Entity
@Table(name="m_saving_ac"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class MSavingAc  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -7584246527312248590L;
	private long MSavingAcNo;
	private MAc MAc;
	private int accountStatusId;
	private int recoveryPeriodId;
	private BigDecimal savedAm;
	private BigDecimal cumulativeSavedAm;
	private BigDecimal savingInstallmentAm;
	private BigDecimal totalIntEnAm;
	private BigDecimal currentFyIntEnAm;
	private BigDecimal prevMonthIntAm;
	private BigDecimal returnedSavedAm;
	private BigDecimal returnedIntEnAm;
	private Integer expNoOfInst;
	private Integer noOfInstPaid;
	private Integer noOfInsallLate;
	private Integer noOfInsallMissed;
	private Date requestedDate;
	private Date approvedDate;
	private Date actualStartDate;
	private Date instStartDate;
	private Date expCompletionDate;
	private Date closureDate;

	// Constructors

	/** default constructor */
	public MSavingAc() {
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="m_saving_ac_no", unique=true, nullable=false, insertable=true, updatable=true)

	public long getMSavingAcNo() {
		return this.MSavingAcNo;
	}

	public void setMSavingAcNo(long MSavingAcNo) {
		this.MSavingAcNo = MSavingAcNo;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="m_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public MAc getMAc() {
		return this.MAc;
	}

	public void setMAc(MAc MAc) {
		this.MAc = MAc;
	}
	@Column(name="account_status_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getAccountStatusId() {
		return this.accountStatusId;
	}

	public void setAccountStatusId(int accountStatusId) {
		this.accountStatusId = accountStatusId;
	}
	@Column(name="recovery_period_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getRecoveryPeriodId() {
		return this.recoveryPeriodId;
	}

	public void setRecoveryPeriodId(int recoveryPeriodId) {
		this.recoveryPeriodId = recoveryPeriodId;
	}
	@Column(name="saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getSavedAm() {
		return this.savedAm;
	}

	public void setSavedAm(BigDecimal savedAm) {
		this.savedAm = savedAm;
	}
	@Column(name="cumulative_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCumulativeSavedAm() {
		return this.cumulativeSavedAm;
	}

	public void setCumulativeSavedAm(BigDecimal cumulativeSavedAm) {
		this.cumulativeSavedAm = cumulativeSavedAm;
	}
	@Column(name="saving_installment_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getSavingInstallmentAm() {
		return this.savingInstallmentAm;
	}

	public void setSavingInstallmentAm(BigDecimal savingInstallmentAm) {
		this.savingInstallmentAm = savingInstallmentAm;
	}
	@Column(name="total_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getTotalIntEnAm() {
		return this.totalIntEnAm;
	}

	public void setTotalIntEnAm(BigDecimal totalIntEnAm) {
		this.totalIntEnAm = totalIntEnAm;
	}
	@Column(name="current_fy_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getCurrentFyIntEnAm() {
		return this.currentFyIntEnAm;
	}

	public void setCurrentFyIntEnAm(BigDecimal currentFyIntEnAm) {
		this.currentFyIntEnAm = currentFyIntEnAm;
	}
	@Column(name="prev_month_int_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPrevMonthIntAm() {
		return this.prevMonthIntAm;
	}

	public void setPrevMonthIntAm(BigDecimal prevMonthIntAm) {
		this.prevMonthIntAm = prevMonthIntAm;
	}
	@Column(name="returned_saved_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getReturnedSavedAm() {
		return this.returnedSavedAm;
	}

	public void setReturnedSavedAm(BigDecimal returnedSavedAm) {
		this.returnedSavedAm = returnedSavedAm;
	}
	@Column(name="returned_int_en_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getReturnedIntEnAm() {
		return this.returnedIntEnAm;
	}

	public void setReturnedIntEnAm(BigDecimal returnedIntEnAm) {
		this.returnedIntEnAm = returnedIntEnAm;
	}
	@Column(name="exp_no_of_inst", unique=false, nullable=true, insertable=true, updatable=true)

	public Integer getExpNoOfInst() {
		return this.expNoOfInst;
	}

	public void setExpNoOfInst(Integer expNoOfInst) {
		this.expNoOfInst = expNoOfInst;
	}
	@Column(name="no_of_inst_paid", unique=false, nullable=true, insertable=true, updatable=true)

	public Integer getNoOfInstPaid() {
		return this.noOfInstPaid;
	}

	public void setNoOfInstPaid(Integer noOfInstPaid) {
		this.noOfInstPaid = noOfInstPaid;
	}
	@Column(name="no_of_insall_late", unique=false, nullable=true, insertable=true, updatable=true)

	public Integer getNoOfInsallLate() {
		return this.noOfInsallLate;
	}

	public void setNoOfInsallLate(Integer noOfInsallLate) {
		this.noOfInsallLate = noOfInsallLate;
	}
	@Column(name="no_of_insall_missed", unique=false, nullable=true, insertable=true, updatable=true)

	public Integer getNoOfInsallMissed() {
		return this.noOfInsallMissed;
	}

	public void setNoOfInsallMissed(Integer noOfInsallMissed) {
		this.noOfInsallMissed = noOfInsallMissed;
	}
	@Column(name="requested_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}
	@Column(name="approved_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}
	@Column(name="actual_start_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getActualStartDate() {
		return this.actualStartDate;
	}

	public void setActualStartDate(Date actualStartDate) {
		this.actualStartDate = actualStartDate;
	}
	@Column(name="inst_start_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getInstStartDate() {
		return this.instStartDate;
	}

	public void setInstStartDate(Date instStartDate) {
		this.instStartDate = instStartDate;
	}
	@Column(name="exp_completion_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getExpCompletionDate() {
		return this.expCompletionDate;
	}

	public void setExpCompletionDate(Date expCompletionDate) {
		this.expCompletionDate = expCompletionDate;
	}
	@Column(name="closure_date", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public Date getClosureDate() {
		return this.closureDate;
	}

	public void setClosureDate(Date closureDate) {
		this.closureDate = closureDate;
	}
}
