package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * NameTitle generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="name_title"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class NameTitle  implements java.io.Serializable {

	// Fields    
	private int titleId;
	private Lang lang;
	private String title;
	private String gender;

	// Constructors

	/** default constructor */
	public NameTitle() {
	}

	/** minimal constructor */
	public NameTitle(Lang lang, String title) {
		this.lang = lang;
		this.title = title;
	}

	/** full constructor */
	public NameTitle(int titleId, Lang lang, String title) {
		this.titleId = titleId;
		this.lang = lang;
		this.title = title;
	}

	/** full constructor */
	public NameTitle(Lang lang, String title, String gender) {
		this.lang = lang;
		this.title = title;
		this.gender = gender;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="title_id", unique=true, nullable=false, insertable=true, updatable=true)
	public int getTitleId() {
		return this.titleId;
	}

	public void setTitleId(int titleId) {
		this.titleId = titleId;
	}
	@ManyToOne(cascade={},
			fetch=FetchType.EAGER)

	@JoinColumn(name="lang_id", unique=false, nullable=false, insertable=true, updatable=true)

	public Lang getLang() {
		return this.lang;
	}

	public void setLang(Lang lang) {
		this.lang = lang;
	}
	@Column(name="title", unique=false, nullable=false, insertable=true, updatable=true, length=10)

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	@Column(name="gender", unique=false, nullable=true, insertable=true, updatable=true, length=10)

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
}
