package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * PaymentMode generated by hbm2java
 */
@Entity
@Table(name="payment_mode"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class PaymentMode  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 9217402128261447847L;
	private int paymentModeId;
	private String paymentModeType;
	private String paymentModeDesc;

	// Constructors

	/** default constructor */
	public PaymentMode() {
	}

	/** minimal constructor */
	public PaymentMode(int paymentModeId, String paymentModeDesc) {
		this.paymentModeId = paymentModeId;
		this.paymentModeDesc = paymentModeDesc;
	}

	/** minimal constructor */
	public PaymentMode(String paymentModeType, String paymentModeDesc) {
		this.paymentModeType = paymentModeType;
		this.paymentModeDesc = paymentModeDesc;
	}

	/** full constructor */
	public PaymentMode(int paymentModeId, String paymentModeType, String paymentModeDesc) {
		this.paymentModeId = paymentModeId;
		this.paymentModeType = paymentModeType;
		this.paymentModeDesc = paymentModeDesc;
	}


	// Property accessors
	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="payment_mode_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getPaymentModeId() {
		return this.paymentModeId;
	}

	public void setPaymentModeId(int paymentModeId) {
		this.paymentModeId = paymentModeId;
	}
	@Column(name="payment_mode_type", unique=false, nullable=true, insertable=true, updatable=true, length=15)

	public String getPaymentModeType() {
		return this.paymentModeType;
	}

	public void setPaymentModeType(String paymentModeType) {
		this.paymentModeType = paymentModeType;
	}
	@Column(name="payment_mode_desc", unique=false, nullable=false, insertable=true, updatable=true, length=100)

	public String getPaymentModeDesc() {
		return this.paymentModeDesc;
	}

	public void setPaymentModeDesc(String paymentModeDesc) {
		this.paymentModeDesc = paymentModeDesc;
	}
}
