package com.beone.shg.net.persistence.model;
// Generated May 22, 2014 2:05:14 AM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReasonToUndo generated by hbm2java
 */
@Entity
@Table(name="reason_to_undo"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class ReasonToUndo  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -132131433801750357L;
	private int reasonId;
	private String reason;
	private String reasonDesc;

	// Constructors

	/** default constructor */
	public ReasonToUndo() {
	}

	/** minimal constructor */
	public ReasonToUndo(String reason, String reasonDesc) {
		this.reason = reason;
		this.reasonDesc = reasonDesc;
	}
	/** minimal constructor */
	public ReasonToUndo(int reasonId, String reason, String reasonDesc) {
		this.reasonId = reasonId;
		this.reason = reason;
		this.reasonDesc = reasonDesc;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="reason_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(int reasonId) {
		this.reasonId = reasonId;
	}
	@Column(name="reason", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	@Column(name="reason_desc", unique=false, nullable=false, insertable=true, updatable=true, length=100)

	public String getReasonDesc() {
		return this.reasonDesc;
	}

	public void setReasonDesc(String reasonDesc) {
		this.reasonDesc = reasonDesc;
	}
}
