package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * RecoveryPeriod generated by hbm2java
 */
@Entity
@Table(name="recovery_period"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class RecoveryPeriod  implements java.io.Serializable {

	private static final long serialVersionUID = 5238537849676327349L;
	private int recoveryPeriodId;
	private String period;
	private String recoveryPeriodDesc;


	// Constructors

	/** default constructor */
	public RecoveryPeriod() {
	}

	/** minimal constructor */
	public RecoveryPeriod(String period, String recoveryPeriodDesc) {
		this.period = period;
		this.recoveryPeriodDesc = recoveryPeriodDesc;
	}

	/** full constructor */
	public RecoveryPeriod(int recoveryPeriodId, String period, String recoveryPeriodDesc) {
		this.recoveryPeriodId = recoveryPeriodId;
		this.period = period;
		this.recoveryPeriodDesc = recoveryPeriodDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="recovery_period_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getRecoveryPeriodId() {
		return this.recoveryPeriodId;
	}

	public void setRecoveryPeriodId(int recoveryPeriodId) {
		this.recoveryPeriodId = recoveryPeriodId;
	}
	@Column(name="period", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}
	@Column(name="recovery_period_desc", unique=false, nullable=false, insertable=true, updatable=true, length=100)

	public String getRecoveryPeriodDesc() {
		return this.recoveryPeriodDesc;
	}

	public void setRecoveryPeriodDesc(String recoveryPeriodDesc) {
		this.recoveryPeriodDesc = recoveryPeriodDesc;
	}

}
