package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TxStatus generated by hbm2java
 */
@Entity
@Table(name="tx_status"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class TxStatus  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -2991834644865552763L;
	private int txStatusId;
	private String txStatus;
	private String txStatusDesc;

	// Constructors

	/** default constructor */
	public TxStatus() {
	}

	/** minimal constructor */
	public TxStatus(int txStatusId, String txStatus) {
		this.txStatusId = txStatusId;
		this.txStatus = txStatus;
	}

	/** constructor */
	public TxStatus(String txStatus, String txStatusDesc) {
		this.txStatus = txStatus;
		this.txStatusDesc = txStatusDesc;
	}

	/** full constructor */
	public TxStatus(int txStatusId, String txStatus, String txStatusDesc) {
		this.txStatusId = txStatusId;
		this.txStatus = txStatus;
		this.txStatusDesc = txStatusDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="tx_status_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getTxStatusId() {
		return this.txStatusId;
	}

	public void setTxStatusId(int txStatusId) {
		this.txStatusId = txStatusId;
	}
	@Column(name="tx_status", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getTxStatus() {
		return this.txStatus;
	}

	public void setTxStatus(String txStatus) {
		this.txStatus = txStatus;
	}
	@Column(name="tx_status_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getTxStatusDesc() {
		return this.txStatusDesc;
	}

	public void setTxStatusDesc(String txStatusDesc) {
		this.txStatusDesc = txStatusDesc;
	}

}
