package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:17 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MTxTodo generated by hbm2java
 */
@Entity
@Table(name="tx_todo"
,catalog="shg"
, uniqueConstraints = {  }
		)
public class TxTodo  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -6007061649085125440L;
	private long txTodoId;
	private long groupAcNo;
	private long memberAcNo;
	private long bankGroupAcNo;
	private long memberLoanAcNo;
	private long memberSavingAcNo;
	private long groupLoanAcNo;
	private int txTypeId;
	private int expectedPaymentModeId;
	private int txTodoStatusId;
	private BigDecimal amount;
	private BigDecimal interestComponent;
	private BigDecimal penaltyAm;
	private BigDecimal penaltyPaidAm;
	private Date dueDate;
	private String description;
	private Date creationOnTs;
	private Date doneOnTs;
	private Set<Tx> txs = new HashSet<Tx>(0);

	// Constructors
	/** default constructor */
	public TxTodo() {
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="tx_todo_id", unique=true, nullable=false, insertable=true, updatable=true)

	public long getTxTodoId() {
		return this.txTodoId;
	}

	public void setTxTodoId(long txTodoId) {
		this.txTodoId = txTodoId;
	}
	@Column(name="g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getGroupAcNo() {
		return this.groupAcNo;
	}

	public void setGroupAcNo(long groupAcNo) {
		this.groupAcNo = groupAcNo;
	}
	@Column(name="m_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getMemberAcNo() {
		return this.memberAcNo;
	}

	public void setMemberAcNo(long memberAcNo) {
		this.memberAcNo = memberAcNo;
	}
	@Column(name="b_g_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getBankGroupAcNo() {
		return bankGroupAcNo;
	}

	public void setBankGroupAcNo(long bankGroupAcNo) {
		this.bankGroupAcNo = bankGroupAcNo;
	}
	@Column(name="m_loan_ac_no", unique=false, nullable=true, insertable=true, updatable=true)

	public long getMemberLoanAcNo() {
		return this.memberLoanAcNo;
	}

	public void setMemberLoanAcNo(long memberLoanAcNo) {
		this.memberLoanAcNo = memberLoanAcNo;
	}
	@Column(name="m_saving_ac_no", unique=false, nullable=true, insertable=true, updatable=true)

	public long getMemberSavingAcNo() {
		return this.memberSavingAcNo;
	}

	public void setMemberSavingAcNo(long memberSavingAcNo) {
		this.memberSavingAcNo = memberSavingAcNo;
	}
	@Column(name="g_loan_ac_no", unique=false, nullable=false, insertable=true, updatable=true)

	public long getGroupLoanAcNo() {
		return groupLoanAcNo;
	}

	public void setGroupLoanAcNo(long groupLoanAcNo) {
		this.groupLoanAcNo = groupLoanAcNo;
	}
	@Column(name="tx_type_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getTxTypeId() {
		return this.txTypeId;
	}

	public void setTxTypeId(int txTypeId) {
		this.txTypeId = txTypeId;
	}
	@Column(name="expected_pmt_mode", unique=false, nullable=true, insertable=true, updatable=true)

	public int getExpectedPaymentModeId() {
		return this.expectedPaymentModeId;
	}

	public void setExpectedPaymentModeId(int expectedPaymentModeId) {
		this.expectedPaymentModeId = expectedPaymentModeId;
	}
	@Column(name="tx_todo_status_id", unique=false, nullable=false, insertable=true, updatable=true)

	public int getTxTodoStatusId() {
		return this.txTodoStatusId;
	}

	public void setTxTodoStatusId(int txTodoStatusId) {
		this.txTodoStatusId = txTodoStatusId;
	}
	@Column(name="amount", unique=false, nullable=false, insertable=true, updatable=true, precision=16)

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	@Column(name="interest_component", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getInterestComponent() {
		return this.interestComponent;
	}

	public void setInterestComponent(BigDecimal interestComponent) {
		this.interestComponent = interestComponent;
	}
	@Column(name="penalty_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPenaltyAm() {
		return this.penaltyAm;
	}

	public void setPenaltyAm(BigDecimal penaltyAm) {
		this.penaltyAm = penaltyAm;
	}
	@Column(name="penalty_paid_am", unique=false, nullable=true, insertable=true, updatable=true, precision=16)

	public BigDecimal getPenaltyPaidAm() {
		return this.penaltyPaidAm;
	}

	public void setPenaltyPaidAm(BigDecimal penaltyPaidAm) {
		this.penaltyPaidAm = penaltyPaidAm;
	}
	@Column(name="due_date", unique=false, nullable=false, insertable=true, updatable=true, length=10)

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}
	@Column(name="description", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		if(description != null && description.length() > 100) {
			this.description = description.substring(0, 99);
		} else {
			this.description = description;
		}
	}
	@Column(name="creation_on_ts", unique=false, nullable=true, insertable=true, updatable=true, length=19)

	public Date getCreationOnTs() {
		return this.creationOnTs;
	}

	public void setCreationOnTs(Date creationOnTs) {
		this.creationOnTs = creationOnTs;
	}
	@Column(name="done_on_ts", unique=false, nullable=true, insertable=true, updatable=true, length=19)

	public Date getDoneOnTs() {
		return this.doneOnTs;
	}

	public void setDoneOnTs(Date doneOnTs) {
		this.doneOnTs = doneOnTs;
	}
	@OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="txTodo")

	public Set<Tx> getTxs() {
		return this.txs;
	}

	public void setTxs(Set<Tx> txs) {
		this.txs = txs;
	}
}
