package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:18 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TxTodoStatus generated by hbm2java
 */
@Entity
@Table(name="tx_todo_status"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class TxTodoStatus  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = -3670300953782762608L;
	private int txTodoStatusId;
	private String txTodoStatus;
	private String txTodoStatusDesc;

	// Constructors

	/** default constructor */
	public TxTodoStatus() {
	}

	/** minimal constructor */
	public TxTodoStatus(int txTodoStatusId, String txTodoStatus) {
		this.txTodoStatusId = txTodoStatusId;
		this.txTodoStatus = txTodoStatus;
	}

	/**  constructor */
	public TxTodoStatus(String txTodoStatus, String txTodoStatusDesc) {
		this.txTodoStatus = txTodoStatus;
		this.txTodoStatusDesc = txTodoStatusDesc;
	}

	/** full constructor */
	public TxTodoStatus(int txTodoStatusId, String txTodoStatus, String txTodoStatusDesc) {
		this.txTodoStatusId = txTodoStatusId;
		this.txTodoStatus = txTodoStatus;
		this.txTodoStatusDesc = txTodoStatusDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="tx_todo_status_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getTxTodoStatusId() {
		return this.txTodoStatusId;
	}

	public void setTxTodoStatusId(int txTodoStatusId) {
		this.txTodoStatusId = txTodoStatusId;
	}
	@Column(name="tx_todo_status", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getTxTodoStatus() {
		return this.txTodoStatus;
	}

	public void setTxTodoStatus(String txTodoStatus) {
		this.txTodoStatus = txTodoStatus;
	}
	@Column(name="tx_todo_status_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getTxTodoStatusDesc() {
		return this.txTodoStatusDesc;
	}

	public void setTxTodoStatusDesc(String txTodoStatusDesc) {
		this.txTodoStatusDesc = txTodoStatusDesc;
	}

}
