package com.beone.shg.net.persistence.model;
// Generated Mar 22, 2014 6:10:19 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TxType generated by hbm2java
 */
@Entity
@Table(name="tx_type"
,catalog="shg"
, uniqueConstraints = {  }
		)

public class TxType  implements java.io.Serializable {

	// Fields    
	private static final long serialVersionUID = 7741384124499562683L;
	private int txTypeId;
	private String txName;
	private String txCategory;
	private String slipType;
	private String amountType;
	private String txWith;
	private String txTypeDesc;
	private String updateFormulaOnDone;
	private String updateFormulaOnUndone;
	private String updateFormulaOnApprove;
	private String updateFormulaOnReject;


	// Constructors

	/** default constructor */
	public TxType() {
	}

	/** minimal constructor */
	public TxType(int txTypeId, String txName, String txCategory, String slipType, String amountType) {
		this.txTypeId = txTypeId;
		this.txName = txName;
		this.txCategory = txCategory;
		this.slipType = slipType;
		this.amountType = amountType;
	}

	/** full constructor */
	public TxType(String txName, String txCategory, String slipType, String amountType, String txWith, String txTypeDesc) {
		this.txName = txName;
		this.txCategory = txCategory;
		this.slipType = slipType;
		this.amountType = amountType;
		this.txWith = txWith;
		this.txTypeDesc = txTypeDesc;
	}

	/** full constructor */
	public TxType(int txTypeId, String txName, String txCategory, String slipType, String amountType, String txWith, String txTypeDesc) {
		this.txTypeId = txTypeId;
		this.txName = txName;
		this.txCategory = txCategory;
		this.slipType = slipType;
		this.amountType = amountType;
		this.txWith = txWith;
		this.txTypeDesc = txTypeDesc;
	}


	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="tx_type_id", unique=true, nullable=false, insertable=true, updatable=true)

	public int getTxTypeId() {
		return this.txTypeId;
	}

	public void setTxTypeId(int txTypeId) {
		this.txTypeId = txTypeId;
	}
	@Column(name="tx_name", unique=false, nullable=false, insertable=true, updatable=true, length=30)

	public String getTxName() {
		return this.txName;
	}

	public void setTxName(String txName) {
		this.txName = txName;
	}
	@Column(name="tx_category", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getTxCategory() {
		return txCategory;
	}

	public void setTxCategory(String txCategory) {
		this.txCategory = txCategory;
	}

	@Column(name="slip_type", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getSlipType() {
		return this.slipType;
	}

	public void setSlipType(String slipType) {
		this.slipType = slipType;
	}
	@Column(name="amount_type", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getAmountType() {
		return this.amountType;
	}

	public void setAmountType(String amountType) {
		this.amountType = amountType;
	}
	@Column(name="tx_with", unique=false, nullable=false, insertable=true, updatable=true, length=20)

	public String getTxWith() {
		return this.txWith;
	}

	public void setTxWith(String txWith) {
		this.txWith = txWith;
	}
	@Column(name="tx_type_desc", unique=false, nullable=true, insertable=true, updatable=true, length=100)

	public String getTxTypeDesc() {
		return this.txTypeDesc;
	}

	public void setTxTypeDesc(String txTypeDesc) {
		this.txTypeDesc = txTypeDesc;
	}
	@Column(name="update_formula_on_done", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getUpdateFormulaOnDone() {
		return updateFormulaOnDone;
	}

	public void setUpdateFormulaOnDone(String updateFormulaOnDone) {
		this.updateFormulaOnDone = updateFormulaOnDone;
	}
	@Column(name="update_formula_on_undone", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getUpdateFormulaOnUndone() {
		return updateFormulaOnUndone;
	}

	public void setUpdateFormulaOnUndone(String updateFormulaOnUndone) {
		this.updateFormulaOnUndone = updateFormulaOnUndone;
	}
	@Column(name="update_formula_on_approve", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getUpdateFormulaOnApprove() {
		return updateFormulaOnApprove;
	}

	public void setUpdateFormulaOnApprove(String updateFormulaOnApprove) {
		this.updateFormulaOnApprove = updateFormulaOnApprove;
	}
	@Column(name="update_formula_on_reject", unique=false, nullable=true, insertable=true, updatable=true, length=500)

	public String getUpdateFormulaOnReject() {
		return updateFormulaOnReject;
	}

	public void setUpdateFormulaOnReject(String updateFormulaOnReject) {
		this.updateFormulaOnReject = updateFormulaOnReject;
	}
}
