-- MySQL Script generated by MySQL Workbench
-- 01/04/15 21:16:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shg` DEFAULT CHARACTER SET utf8 ;
USE `shg` ;

-- -----------------------------------------------------
-- Table `shg`.`investment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`investment_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`investment_type` (
  `investment_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `investment_type` VARCHAR(30) NOT NULL,
  `investment_type_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`investment_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`active_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`active_status` ;

CREATE TABLE IF NOT EXISTS `shg`.`active_status` (
  `active_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `active_status` VARCHAR(20) NOT NULL,
  `active_status_desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`active_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`approval_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`approval_status` ;

CREATE TABLE IF NOT EXISTS `shg`.`approval_status` (
  `approval_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `approval_status` VARCHAR(20) NOT NULL,
  `approval_status_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`approval_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`g_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_profile` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_profile` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `approval_status_id` INT(10) UNSIGNED NOT NULL,
  `active_status_id` INT(10) UNSIGNED NOT NULL,
  `group_type_id` INT(10) UNSIGNED NOT NULL,
  `approved_by_m` BIGINT(20) NULL,
  `member_counter` INT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `percentage_pro_comp` FLOAT NULL,
  `active_child_groups` INT(10) NULL,
  `active_core_members` INT(10) ZEROFILL NULL DEFAULT NULL,
  `active_associate_members` INT(10) ZEROFILL NULL DEFAULT NULL,
  `no_of_top_g` INT(10) ZEROFILL NULL DEFAULT NULL,
  `no_of_down_g` INT(10) ZEROFILL NULL DEFAULT NULL,
  `registration_no` VARCHAR(15) NULL DEFAULT NULL,
  `profile_code` BLOB NULL DEFAULT NULL,
  `last_logged_in_ts` TIMESTAMP NULL DEFAULT NULL,
  `establishment_date` DATE NULL,
  `approval_date` DATE NULL DEFAULT NULL,
  `date_of_registration` DATE NULL DEFAULT NULL,
  `logo_url` VARCHAR(100) NULL DEFAULT NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `location` VARCHAR(100) NULL,
  PRIMARY KEY (`g_ac_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`bank_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`bank_profile` ;

CREATE TABLE IF NOT EXISTS `shg`.`bank_profile` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `ifcs_code` VARCHAR(12) NOT NULL,
  `bank_name` VARCHAR(40) NOT NULL,
  `branch_name` VARCHAR(25) NOT NULL,
  `bank_loan_int_rate` FLOAT NULL,
  `bank_fd_int_rate` FLOAT NULL,
  `bank_rating` FLOAT NULL,
  `loan_processing_fee` INT(10) NULL,
  `loan_application_charges` INT(10) NULL,
  `loan_prepayment_charges` INT(10) NULL,
  `late_payment_charges` INT(10) NULL,
  `missed_payment_charges` INT(10) NULL,
  INDEX `bank_profile_ibfk_1_idx` (`g_ac_no` ASC),
  CONSTRAINT `bank_profile_ibfk_1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`bank_account` ;

CREATE TABLE IF NOT EXISTS `shg`.`bank_account` (
  `bank_account_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `account_type_id` INT(10) UNSIGNED NOT NULL,
  `b_g_ac_no` BIGINT(20) NOT NULL,
  `account_name` VARCHAR(50) NULL DEFAULT NULL,
  `account_number` VARCHAR(25) NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`bank_account_no`),
  INDEX `bank_account_ibfk_2_idx` (`b_g_ac_no` ASC),
  CONSTRAINT `bank_account_ibfk_2`
    FOREIGN KEY (`b_g_ac_no`)
    REFERENCES `shg`.`bank_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`bank_account_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`bank_account_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`bank_account_type` (
  `account_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(20) NOT NULL,
  `account_type_desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`account_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`lang` ;

CREATE TABLE IF NOT EXISTS `shg`.`lang` (
  `lang_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang` VARCHAR(15) NOT NULL,
  `lang_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`district` ;

CREATE TABLE IF NOT EXISTS `shg`.`district` (
  `district_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(20) NOT NULL,
  `division` VARCHAR(20) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `lang_id` INT(10) UNSIGNED NOT NULL,
  `district_code` CHAR(5) NULL DEFAULT NULL,
  `group_counter` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`district_id`),
  INDEX `district_FKIndex1` (`lang_id` ASC),
  CONSTRAINT `district_ibfk_1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `shg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`contact` ;

CREATE TABLE IF NOT EXISTS `shg`.`contact` (
  `contact_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `district_id` INT(10) UNSIGNED NOT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `village` VARCHAR(25) NULL DEFAULT NULL,
  `grampanchayat` VARCHAR(25) NULL DEFAULT NULL,
  `taluka` VARCHAR(25) NULL DEFAULT NULL,
  `pin_code` VARCHAR(8) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `pri_mobile` VARCHAR(15) NULL DEFAULT NULL,
  `sec_mobile` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `contact_FKIndex1` (`district_id` ASC),
  CONSTRAINT `contact_ibfk_1`
    FOREIGN KEY (`district_id`)
    REFERENCES `shg`.`district` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`g_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_ac` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `credit_rating` FLOAT NULL DEFAULT NULL,
  `approval_rating` FLOAT NULL DEFAULT NULL,
  `meeting_attendance` FLOAT NULL DEFAULT NULL,
  `c_m_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_planned_monthly_saving` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_returned_int_en_am` DECIMAL(16,2) NULL,
  `c_m_profit_share_declared_am` DECIMAL(16,2) NULL,
  `c_m_profit_share_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_no_of_loans` INT(10) NULL,
  `c_m_no_of_active_loans` INT(10) NULL,
  `c_m_bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_no_of_bad_dept_loans` INT(10) NULL,
  `a_m_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_planned_monthly_saving` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_returned_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_divided_declared_am` DECIMAL(16,2) NULL,
  `a_m_divided_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_no_of_loans` INT(10) NULL,
  `a_m_no_of_active_loans` INT(10) NULL,
  `a_m_bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_no_of_bad_dept_loans` INT(10) NULL,
  `p_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_project` INT(10) NULL,
  `no_of_active_project` INT(10) NULL,
  `fix_deposit_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_fix_deposit` INT(10) NULL,
  `no_of_active_fix_deposit` INT(10) NULL,
  `other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_other_inv` INT(10) NULL,
  `no_of_active_other_inv` INT(10) NULL,
  `int_en_on_saving_ac_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `net_profit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `expenses_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_int_on_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `bad_bank_loan_dept_am` DECIMAL(16,2) NULL,
  `no_of_bank_loan` INT(10) NULL,
  `no_of_active_bank_loan` INT(10) NULL,
  `pen_shg_one_mem_reg_fee` DECIMAL(16,2) NULL DEFAULT NULL,
  `pen_shg_one_service_charges` DECIMAL(16,2) NULL DEFAULT NULL,
  `clear_bank_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_bank_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `clear_cash_in_hand_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_cash_in_hand_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `last_updated_ts` TIMESTAMP NULL DEFAULT NULL,
  INDEX `g_ac_FKIndex1` (`g_ac_no` ASC),
  CONSTRAINT `g_ac_ibfk_1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`g_bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_bank_account` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_bank_account` (
  `bank_account_no` BIGINT(20) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `clear_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `verified_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `penalty_charges_am` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`bank_account_no`),
  INDEX `g_bank_acount_FKIndex1` (`g_ac_no` ASC),
  INDEX `g_bank_acount_FKIndex2` (`bank_account_no` ASC),
  CONSTRAINT `g_bank_account_ibfk_1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `g_bank_account_ibfk_2`
    FOREIGN KEY (`bank_account_no`)
    REFERENCES `shg`.`bank_account` (`bank_account_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`g_invt_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_invt_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_invt_ac` (
  `g_invt_ac_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `g_ac_no` BIGINT(20) NOT NULL,
  `b_g_ac_no` BIGINT(20) NOT NULL,
  `invt_bank_ac_no` BIGINT(20) NOT NULL,
  `investment_type_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `investment_no` VARCHAR(20) NULL DEFAULT NULL,
  `investment_ac_name` VARCHAR(50) NULL DEFAULT NULL,
  `investment_desc` VARCHAR(200) NULL DEFAULT NULL,
  `approved_by_m` BIGINT(20) NULL DEFAULT NULL,
  `invt_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_invt_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `interest_rate` FLOAT NULL DEFAULT NULL,
  `requested_date` DATE NULL DEFAULT NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `maturity_date` DATE NULL DEFAULT NULL,
  `closure_date` DATE NULL DEFAULT NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  `development_plan` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`g_invt_ac_no`),
  INDEX `g_invt_ac_ibfk_1_idx` (`g_ac_no` ASC),
  CONSTRAINT `g_invt_ac_ibfk_1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_ac` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`g_loan_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_loan_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_loan_ac` (
  `g_loan_ac_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `g_ac_no` BIGINT(20) NOT NULL,
  `b_g_ac_no` BIGINT(20) NOT NULL,
  `loan_bank_ac_no` BIGINT(20) NOT NULL,
  `recovery_period_id` INT(10) UNSIGNED NOT NULL,
  `fund_type_id` INT(10) UNSIGNED NOT NULL,
  `loan_calculation_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `loan_source_id` INT(10) UNSIGNED NOT NULL,
  `loan_ac_name` VARCHAR(50) NULL,
  `approved_by_m` BIGINT(20) NULL DEFAULT NULL,
  `principle_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_principle_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `installment_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pre_emi_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_interest_due_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `interest_rate` FLOAT NULL DEFAULT NULL,
  `exp_no_of_inst` INT(10) UNSIGNED NULL DEFAULT NULL,
  `startup_no_of_inst` INT(10) NULL,
  `no_of_inst_paid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `no_of_insall_missed` INT(10) NULL,
  `no_of_insall_late` INT(10) NULL,
  `requested_date` DATE NULL DEFAULT NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `disbursement_date` DATE NULL DEFAULT NULL,
  `inst_start_date` DATE NULL DEFAULT NULL,
  `exp_completion_date` DATE NULL DEFAULT NULL,
  `closure_date` DATE NULL DEFAULT NULL,
  `development_plan` VARCHAR(500) NULL DEFAULT NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`g_loan_ac_no`),
  INDEX `g_loan_ac_ibfk_1_idx` (`g_ac_no` ASC),
  CONSTRAINT `g_loan_ac_ibfk_1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_ac` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`g_m`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_m` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_m` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `ws_access_rights` BIGINT(20) NULL,
  `ui_access_rights` BIGINT(20) NULL,
  PRIMARY KEY (`g_ac_no`, `m_ac_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`group_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`group_contact` ;

CREATE TABLE IF NOT EXISTS `shg`.`group_contact` (
  `contact_id` BIGINT(20) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `lang_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `vision` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `group_contact_FKIndex1` (`contact_id` ASC),
  INDEX `group_contact_FKIndex2` (`g_ac_no` ASC),
  INDEX `group_contact_FKIndex3` (`lang_id` ASC),
  CONSTRAINT `group_contact_ibfk_1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `shg`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_contact_ibfk_2`
    FOREIGN KEY (`lang_id`)
    REFERENCES `shg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_contact_ibfk_3`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`language_massage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`language_massage` ;

CREATE TABLE IF NOT EXISTS `shg`.`language_massage` (
  `massage_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang_id` INT(10) UNSIGNED NOT NULL,
  `massage_key` VARCHAR(45) NULL,
  `massage` VARCHAR(100) NULL,
  `massage_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`massage_id`, `lang_id`),
  INDEX `fk_language_massage_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_language_massage_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `shg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_profile` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_profile` (
  `m_ac_no` BIGINT(20) NOT NULL,
  `m_role_id` INT(10) UNSIGNED NOT NULL,
  `approval_status_id` INT(10) UNSIGNED NOT NULL,
  `active_status_id` INT(10) UNSIGNED NOT NULL,
  `passcode` VARCHAR(20) NULL DEFAULT NULL,
  `pass_set` TINYINT NULL,
  `profile_code` BLOB NULL DEFAULT NULL,
  `date_of_enroll` DATE NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `date_of_anni` DATE NULL DEFAULT NULL,
  `date_of_closure` DATE NULL DEFAULT NULL,
  `last_logged_in_ts` TIMESTAMP NULL DEFAULT NULL,
  `approved_by_m` BIGINT(20) NULL DEFAULT NULL,
  `reco_by_m` BIGINT(20) NULL DEFAULT NULL,
  `gender` ENUM('Male', 'Female', 'Unknow') NULL,
  `percentage_pro_comp` FLOAT NULL,
  `uidai_no` VARCHAR(20) NULL DEFAULT NULL,
  `pan_card_no` VARCHAR(20) NULL DEFAULT NULL,
  `voter_id_no` VARCHAR(20) NULL DEFAULT NULL,
  `driving_license_no` VARCHAR(20) NULL DEFAULT NULL,
  `photo_url` VARCHAR(100) NULL DEFAULT NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `location` VARCHAR(100) NULL,
  PRIMARY KEY (`m_ac_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_ac` (
  `m_ac_no` BIGINT(20) NOT NULL,
  `credit_rating` FLOAT NULL DEFAULT NULL,
  `saved_am` DECIMAL(16,2) NULL,
  `prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `returned_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `divided_profit_declared_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `divided_profit_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `last_updated_ts` TIMESTAMP NULL DEFAULT NULL,
  `planned_monthly_saving_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `prev_month_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_loans` INT(10) NULL,
  `no_of_active_loans` INT(10) NULL,
  `meeting_attendance` FLOAT NULL,
  `meeting_attended` INT(10) NULL,
  `meeting_missed` INT(10) NULL,
  PRIMARY KEY (`m_ac_no`),
  INDEX `m_ac_FKIndex1` (`m_ac_no` ASC),
  CONSTRAINT `m_ac_ibfk_1`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_profile` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_bank_account` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_bank_account` (
  `bank_account_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  PRIMARY KEY (`bank_account_no`),
  INDEX `m_bank_account_FKIndex1` (`m_ac_no` ASC),
  INDEX `m_bank_account_FKIndex2` (`bank_account_no` ASC),
  CONSTRAINT `m_bank_account_ibfk_1`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_profile` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `m_bank_account_ibfk_2`
    FOREIGN KEY (`bank_account_no`)
    REFERENCES `shg`.`bank_account` (`bank_account_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`m_saving_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_saving_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_saving_ac` (
  `m_saving_ac_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `m_ac_no` BIGINT(20) NOT NULL,
  `recovery_period_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `saved_am` DECIMAL(16,2) NULL,
  `cumulative_saved_am` DECIMAL(16,2) NULL,
  `saving_installment_am` DECIMAL(16,2) NULL,
  `total_int_en_am` DECIMAL(16,2) NULL,
  `current_fy_int_en_am` DECIMAL(16,2) NULL,
  `prev_month_int_am` DECIMAL(16,2) NULL,
  `returned_saved_am` DECIMAL(16,2) NULL,
  `returned_int_en_am` DECIMAL(16,2) NULL,
  `exp_no_of_inst` INT(10) UNSIGNED NULL,
  `no_of_inst_paid` INT(10) UNSIGNED NULL,
  `no_of_insall_late` INT(10) UNSIGNED NULL,
  `no_of_insall_missed` INT(10) UNSIGNED NULL,
  `requested_date` DATE NULL DEFAULT NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `actual_start_date` DATE NULL DEFAULT NULL,
  `inst_start_date` DATE NULL DEFAULT NULL,
  `exp_completion_date` DATE NULL DEFAULT NULL,
  `closure_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`m_saving_ac_no`),
  INDEX `m_saving_ac_FKIndex3` (`m_ac_no` ASC),
  CONSTRAINT `m_saving_ac_ibfk_1`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_ac` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_role` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_role` (
  `m_role_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `m_role` VARCHAR(30) NOT NULL,
  `m_role_category` VARCHAR(20) NOT NULL,
  `belong_to` VARCHAR(20) NOT NULL,
  `m_role_desc` VARCHAR(100) NULL DEFAULT NULL,
  `default_ws_access_rights` BIGINT(20) NULL,
  `default_ui_access_rights` BIGINT(20) NULL,
  PRIMARY KEY (`m_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`tx`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`tx` ;

CREATE TABLE IF NOT EXISTS `shg`.`tx` (
  `tx_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `g_ac_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NULL,
  `b_g_ac_no` BIGINT(20) NULL,
  `tx_type_id` INT(10) UNSIGNED NOT NULL,
  `tx_status_id` INT(10) UNSIGNED NOT NULL,
  `payment_mode_id` INT(10) UNSIGNED NOT NULL,
  `done_by_m` BIGINT(20) NOT NULL,
  `approved_by_m` BIGINT(20) NULL,
  `tx_todo_id` BIGINT(20) NULL,
  `counter_tx_id` BIGINT(20) NULL,
  `g_bank_account` BIGINT(20) NULL,
  `m_bank_account` BIGINT(20) NULL,
  `b_g_bank_account` BIGINT(20) NULL,
  `m_saving_ac_no` BIGINT(20) NULL,
  `m_loan_ac_no` BIGINT(20) NULL,
  `g_invt_ac_no` BIGINT(20) NULL,
  `g_loan_ac_no` BIGINT(20) NULL,
  `reason_to_undo` INT(10) UNSIGNED NULL,
  `receipt_voucher_no` VARCHAR(12) NULL,
  `cheque_no` VARCHAR(12) NULL,
  `amount` DECIMAL(16,2) NULL,
  `payment_ts` TIMESTAMP NULL DEFAULT NULL,
  `entry_ts` TIMESTAMP NULL DEFAULT NULL,
  `approved_ts` TIMESTAMP NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `entry_location` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`tx_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`tx_todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`tx_todo` ;

CREATE TABLE IF NOT EXISTS `shg`.`tx_todo` (
  `tx_todo_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `m_ac_no` BIGINT(20) NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `b_g_ac_no` BIGINT(20) NULL,
  `tx_type_id` INT(10) UNSIGNED NOT NULL,
  `tx_todo_status_id` INT(10) UNSIGNED NOT NULL,
  `m_saving_ac_no` BIGINT(20) NULL,
  `m_loan_ac_no` BIGINT(20) NULL,
  `g_loan_ac_no` BIGINT(20) NULL,
  `expected_pmt_mode` INT(10) UNSIGNED NULL DEFAULT NULL,
  `amount` DECIMAL(16,2) NOT NULL,
  `interest_component` DECIMAL(16,2) NULL DEFAULT NULL,
  `penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `due_date` DATE NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `creation_on_ts` TIMESTAMP NULL,
  `done_on_ts` TIMESTAMP NULL,
  PRIMARY KEY (`tx_todo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`name_title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`name_title` ;

CREATE TABLE IF NOT EXISTS `shg`.`name_title` (
  `title_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(10) NOT NULL,
  `gender` ENUM('Male', 'Female', 'Unknow') NULL,
  PRIMARY KEY (`title_id`),
  INDEX `name_title_FKIndex1` (`lang_id` ASC),
  CONSTRAINT `name_title_ibfk_1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `shg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`member_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`member_contact` ;

CREATE TABLE IF NOT EXISTS `shg`.`member_contact` (
  `contact_id` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `lang_id` INT(10) UNSIGNED NOT NULL,
  `title_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(20) NULL DEFAULT NULL,
  `middle_name` VARCHAR(20) NULL DEFAULT NULL,
  `last_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `member_contact_FKIndex1` (`contact_id` ASC),
  INDEX `member_contact_FKIndex2` (`title_id` ASC),
  INDEX `member_contact_FKIndex3` (`lang_id` ASC),
  INDEX `member_contact_FKIndex4` (`m_ac_no` ASC),
  CONSTRAINT `member_contact_ibfk_1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `shg`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_contact_ibfk_2`
    FOREIGN KEY (`title_id`)
    REFERENCES `shg`.`name_title` (`title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_contact_ibfk_3`
    FOREIGN KEY (`lang_id`)
    REFERENCES `shg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_contact_ibfk_4`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_profile` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`payment_mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`payment_mode` ;

CREATE TABLE IF NOT EXISTS `shg`.`payment_mode` (
  `payment_mode_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `payment_mode_type` VARCHAR(15) NOT NULL COMMENT 'CASH,CHEQUE,A2A,OLBNK,DEBT,CRDT,DD',
  `payment_mode_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_mode_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`recovery_period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`recovery_period` ;

CREATE TABLE IF NOT EXISTS `shg`.`recovery_period` (
  `recovery_period_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(20) NOT NULL,
  `recovery_period_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`recovery_period_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`tx_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`tx_status` ;

CREATE TABLE IF NOT EXISTS `shg`.`tx_status` (
  `tx_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tx_status` VARCHAR(20) NOT NULL,
  `tx_status_desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`tx_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`tx_todo_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`tx_todo_status` ;

CREATE TABLE IF NOT EXISTS `shg`.`tx_todo_status` (
  `tx_todo_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tx_todo_status` VARCHAR(20) NOT NULL COMMENT '\"PENDING\",\"DONE\",\"UNDONE\",\"OVERDUE\",\"MISSED\",\"CANCELLED\"',
  `tx_todo_status_desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`tx_todo_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`tx_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`tx_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`tx_type` (
  `tx_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tx_name` VARCHAR(30) NOT NULL,
  `tx_category` VARCHAR(20) NOT NULL,
  `slip_type` VARCHAR(20) NOT NULL,
  `amount_type` VARCHAR(20) NOT NULL,
  `tx_with` VARCHAR(20) NOT NULL,
  `tx_type_desc` VARCHAR(100) NULL DEFAULT NULL,
  `update_formula_on_done` VARCHAR(500) NULL DEFAULT NULL,
  `update_formula_on_undone` VARCHAR(500) NULL DEFAULT NULL,
  `update_formula_on_approve` VARCHAR(500) NULL DEFAULT NULL,
  `update_formula_on_reject` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`tx_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_report` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_report` (
  `monthly_report_id` INT(10) NOT NULL AUTO_INCREMENT,
  `report_name` VARCHAR(30) NULL,
  `report_display_name` VARCHAR(45) NULL,
  `report_desc` VARCHAR(200) NULL,
  PRIMARY KEY (`monthly_report_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_report_sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_report_sheet` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_report_sheet` (
  `monthly_report_sheet_id` INT(10) NOT NULL AUTO_INCREMENT,
  `monthly_report_id` INT(10) NOT NULL,
  `report_sheet_name` VARCHAR(50) NULL,
  `report_sheet_top_title` VARCHAR(50) NULL,
  `report_sheet_bottom_title` VARCHAR(50) NULL,
  `sheet_format` VARCHAR(25) NULL,
  `report_sheet_desc` VARCHAR(200) NULL,
  `report_sheet_formula` VARCHAR(2000) NULL,
  PRIMARY KEY (`monthly_report_sheet_id`),
  CONSTRAINT `fk_report_item_mapping_monthly_report1`
    FOREIGN KEY (`monthly_report_id`)
    REFERENCES `shg`.`monthly_report` (`monthly_report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`reason_to_undo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`reason_to_undo` ;

CREATE TABLE IF NOT EXISTS `shg`.`reason_to_undo` (
  `reason_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(20) NOT NULL,
  `reason_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`reason_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`account_status` ;

CREATE TABLE IF NOT EXISTS `shg`.`account_status` (
  `account_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_status` VARCHAR(20) NOT NULL COMMENT '\"PENDING\",\"DONE\",\"UNDONE\",\"OVERDUE\",\"MISSED\",\"CANCELLED\"',
  `account_status_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`account_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_loan_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_loan_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_loan_ac` (
  `m_loan_ac_no` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `m_ac_no` BIGINT(20) NOT NULL,
  `recovery_period_id` INT(10) UNSIGNED NOT NULL,
  `fund_type_id` INT(10) UNSIGNED NOT NULL,
  `loan_calculation_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `loan_source_id` INT(10) UNSIGNED NOT NULL,
  `approved_by_m` BIGINT(20) NULL,
  `principle_am` DECIMAL(16,2) NULL,
  `pending_principle_am` DECIMAL(16,2) NULL,
  `rec_interest_am` DECIMAL(16,2) NULL,
  `proj_interest_am` DECIMAL(16,2) NULL,
  `installment_am` DECIMAL(16,2) NULL,
  `pre_emi_interest_am` DECIMAL(16,2) NULL,
  `pending_interest_due_am` DECIMAL(16,2) NULL,
  `rate_of_interest` FLOAT NULL,
  `startup_no_of_inst` INT(10) UNSIGNED NULL,
  `exp_no_of_inst` INT(10) UNSIGNED NULL,
  `no_of_inst_paid` INT(10) UNSIGNED NULL,
  `no_of_insall_late` INT(10) UNSIGNED NULL,
  `no_of_insall_missed` INT(10) UNSIGNED NULL,
  `requested_date` DATE NULL DEFAULT NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `disbursement_date` DATE NULL DEFAULT NULL,
  `inst_start_date` DATE NULL DEFAULT NULL,
  `exp_completion_date` DATE NULL DEFAULT NULL,
  `closure_date` DATE NULL DEFAULT NULL,
  `development_plan` VARCHAR(500) NULL DEFAULT NULL,
  `attachment_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`m_loan_ac_no`),
  INDEX `m_loan_ac_ibfk_3_idx` (`m_ac_no` ASC),
  CONSTRAINT `m_loan_ac_ibfk_1`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_ac` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`g_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_rules` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_rules` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `max_no_of_core_members` SMALLINT UNSIGNED NULL,
  `allow_associate_members` SMALLINT UNSIGNED NULL,
  `cm_monthly_saving` INT(10) UNSIGNED NULL,
  `am_min_monthly_saving` INT(10) UNSIGNED NULL,
  `am_max_monthly_saving` INT(10) UNSIGNED NULL,
  `cm_registration_fee` SMALLINT UNSIGNED NULL,
  `am_registration_fee` SMALLINT UNSIGNED NULL,
  `cm_saving_late_fee` SMALLINT UNSIGNED NULL,
  `am_saving_late_fee` SMALLINT UNSIGNED NULL,
  `cm_loan_late_fee` SMALLINT UNSIGNED NULL,
  `am_loan_late_fee` SMALLINT UNSIGNED NULL,
  `cheque_bouncing_penalty` SMALLINT UNSIGNED NULL,
  `auto_debit_failure_penalty` SMALLINT UNSIGNED NULL,
  `cm_application_fee` SMALLINT UNSIGNED NULL,
  `am_application_fee` SMALLINT UNSIGNED NULL,
  `cm_loan_processing_fee_percent` FLOAT NULL,
  `am_loan_processing_fee_percent` FLOAT NULL,
  `cm_int_on_saving` FLOAT NULL,
  `am_int_on_saving` FLOAT NULL,
  `add_int_to_saving_after_months` INT(10) UNSIGNED NULL,
  `cm_base_int_on_loan` FLOAT NULL,
  `am_base_int_on_loan` FLOAT NULL,
  `int_on_consumption_loan` FLOAT NULL,
  `individual_dev_loan_range1` INT(10) UNSIGNED NULL,
  `individual_dev_loan_range2` INT(10) UNSIGNED NULL,
  `individual_dev_loan_range3` INT(10) UNSIGNED NULL,
  `int_on_individual_dev_loan_range1` FLOAT NULL,
  `int_on_individual_dev_loan_range2` FLOAT NULL,
  `int_on_individual_dev_loan_range3` FLOAT NULL,
  `int_on_individual_dev_loan_range4` FLOAT NULL,
  `project_dev_loan_range1` INT(10) UNSIGNED NULL,
  `project_dev_loan_range2` INT(10) UNSIGNED NULL,
  `project_dev_loan_range3` INT(10) UNSIGNED NULL,
  `int_on_project_dev_loan_range1` FLOAT NULL,
  `int_on_project_dev_loan_range2` FLOAT NULL,
  `int_on_project_dev_loan_range3` FLOAT NULL,
  `int_on_project_dev_loan_range4` FLOAT NULL,
  `cm_limit_on_consumption_loan` INT(10) UNSIGNED NULL,
  `am_limit_on_consumption_loan` INT(10) UNSIGNED NULL,
  `cm_min_months_to_con_loan` SMALLINT UNSIGNED NULL,
  `am_min_months_to_con_loan` SMALLINT UNSIGNED NULL,
  `cm_saving_x_consumption_loan` INT(10) UNSIGNED NULL,
  `am_saving_x_consumption_loan` INT(10) UNSIGNED NULL,
  `cm_min_months_to_dev_loan` SMALLINT UNSIGNED NULL,
  `am_min_months_to_dev_loan` SMALLINT UNSIGNED NULL,
  `cm_saving_x_dev_loan` FLOAT NULL,
  `am_saving_x_dev_loan` FLOAT UNSIGNED NULL,
  `cm_min_months_int_on_loan` SMALLINT UNSIGNED NULL,
  `am_min_months_int_on_loan` SMALLINT UNSIGNED NULL,
  `credit_rating_loan_pass_above` FLOAT NULL,
  `credit_rating_loan_causion_above` FLOAT NULL,
  `credit_rating_loan_dengerous_above` FLOAT NULL,
  `compute_day_of_month` SMALLINT UNSIGNED NULL,
  `due_day_of_month` SMALLINT UNSIGNED NULL,
  `sms_sub_key` BIGINT(20) UNSIGNED NULL,
  `mail_sub_key` BIGINT(20) UNSIGNED NULL,
  `report_printing_service` BIGINT(20) UNSIGNED NULL,
  `sms_service_lang_id` INT(10) UNSIGNED NOT NULL,
  `mail_service_lang_id` INT(10) UNSIGNED NOT NULL,
  `report_printing_service_lang_id` INT(10) UNSIGNED NOT NULL,
  `activation_flags` BIGINT(20) NULL,
  `shg_one_cm_reg_charge` SMALLINT UNSIGNED NULL,
  `shg_one_am_reg_charge` SMALLINT UNSIGNED NULL,
  `shg_one_cm_loan_pro_fee_percent` FLOAT NULL,
  `shg_one_am_loan_pro_fee_percent` FLOAT NULL,
  `shg_one_min_annual_service_charge` SMALLINT UNSIGNED NULL,
  `shg_one_max_loan_pro_fee_off` SMALLINT UNSIGNED NULL,
  `shg_one_billing_cycle_in_months` SMALLINT UNSIGNED NULL,
  INDEX `g_rules_fk1_idx` (`g_ac_no` ASC),
  CONSTRAINT `g_rules_fk1`
    FOREIGN KEY (`g_ac_no`)
    REFERENCES `shg`.`g_profile` (`g_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`g_ac_by_txtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_ac_by_txtype` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_ac_by_txtype` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `tx_type_id` INT(10) UNSIGNED NOT NULL,
  `amount` DECIMAL(16,2) NULL,
  PRIMARY KEY (`g_ac_no`, `tx_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`group_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`group_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`group_type` (
  `group_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_type` VARCHAR(20) NOT NULL,
  `category` VARCHAR(20) NULL,
  `default_ws_access_rights` BIGINT(20) NULL,
  `default_ui_access_rights` BIGINT(20) NULL,
  `group_type_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`group_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`group_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`group_relation` ;

CREATE TABLE IF NOT EXISTS `shg`.`group_relation` (
  `group_relation_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_relation` VARCHAR(20) NOT NULL,
  `group_relation_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`group_relation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`g_g`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`g_g` ;

CREATE TABLE IF NOT EXISTS `shg`.`g_g` (
  `top_g_ac_no` BIGINT(20) NOT NULL,
  `down_g_ac_no` BIGINT(20) NOT NULL,
  `group_relation_id` INT(10) UNSIGNED NOT NULL,
  `ws_access_rights` VARCHAR(45) NULL,
  `ui_access_rights` VARCHAR(45) NULL,
  PRIMARY KEY (`top_g_ac_no`, `down_g_ac_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`multi_m_to_loan_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`multi_m_to_loan_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`multi_m_to_loan_ac` (
  `m_loan_ac_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `loan_share` FLOAT ZEROFILL NULL,
  INDEX `multi_m_to_loan_ac_FKIndex2` (`m_ac_no` ASC),
  INDEX `multi_m_to_loan_ac_FKIndex1` (`m_loan_ac_no` ASC),
  CONSTRAINT `multi_m_to_loan_ac_ibfk_1`
    FOREIGN KEY (`m_loan_ac_no`)
    REFERENCES `shg`.`m_loan_ac` (`m_loan_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `multi_m_to_loan_ac_ibfk_2`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_ac` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`advance_cheques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`advance_cheques` ;

CREATE TABLE IF NOT EXISTS `shg`.`advance_cheques` (
  `advance_cheques_id` INT(10) UNSIGNED NOT NULL,
  `bank_account_no` BIGINT(20) NOT NULL,
  `cheque_no` INT(10) NOT NULL,
  `used` TINYINT(1) NULL DEFAULT false,
  `deposit_ts` DATE NULL DEFAULT NULL,
  `amount` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`advance_cheques_id`),
  INDEX `advance_cheques_fk1_idx` (`bank_account_no` ASC),
  CONSTRAINT `advance_cheques_fk1`
    FOREIGN KEY (`bank_account_no`)
    REFERENCES `shg`.`bank_account` (`bank_account_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`fund_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`fund_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`fund_type` (
  `fund_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fund_type` VARCHAR(35) NOT NULL,
  `fund_category` VARCHAR(25) NOT NULL,
  `fund_type_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`fund_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`loan_calculation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`loan_calculation` ;

CREATE TABLE IF NOT EXISTS `shg`.`loan_calculation` (
  `loan_calculation_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loan_calculation` VARCHAR(30) NOT NULL,
  `loan_calculation_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`loan_calculation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`nominee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`nominee` ;

CREATE TABLE IF NOT EXISTS `shg`.`nominee` (
  `nominee_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `m_ac_no` BIGINT(20) NOT NULL,
  `contact_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `relation` VARCHAR(40) NOT NULL,
  `share` FLOAT NULL DEFAULT 1.0,
  PRIMARY KEY (`nominee_id`),
  INDEX `nominee_ibfk_1_idx_idx` (`contact_id` ASC),
  INDEX `nominee_ibfk_2_idx_idx` (`m_ac_no` ASC),
  CONSTRAINT `nominee_ibfk_1_idx`
    FOREIGN KEY (`contact_id`)
    REFERENCES `shg`.`contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nominee_ibfk_2_idx`
    FOREIGN KEY (`m_ac_no`)
    REFERENCES `shg`.`m_profile` (`m_ac_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_g_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_g_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_g_ac` (
  `g_ac_no` BIGINT(20) NOT NULL,
  `month` VARCHAR(10) NOT NULL,
  `credit_rating` FLOAT NULL DEFAULT NULL,
  `approval_rating` FLOAT NULL DEFAULT NULL,
  `meeting_attendance` FLOAT NULL DEFAULT NULL,
  `c_m_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_planned_monthly_saving` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_returned_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_profit_share_declared_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_profit_share_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_pending_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_no_of_loans` INT(10) NULL,
  `c_m_no_of_active_loans` INT(10) NULL,
  `c_m_bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `c_m_no_of_bad_dept_loans` INT(10) NULL,
  `a_m_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_planned_monthly_saving` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_returned_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_divided_declared_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_divided_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_pending_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_no_of_loans` INT(10) NULL,
  `a_m_no_of_active_loans` INT(10) NULL,
  `a_m_bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `a_m_no_of_bad_dept_loans` INT(10) NULL,
  `p_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_pending_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `p_proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_project` INT(10) NULL,
  `no_of_active_project` INT(10) NULL,
  `fix_deposit_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_fix_deposit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_fix_deposit` INT(10) NULL,
  `no_of_active_fix_deposit` INT(10) NULL,
  `other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_other_inv_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_other_inv` INT(10) NULL,
  `no_of_active_other_inv` INT(10) NULL,
  `int_en_on_saving_ac_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `net_profit_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `expenses_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_int_on_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_borrowed_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_bank_loan` INT(10) NULL,
  `no_of_active_bank_loan` INT(10) NULL,
  `clear_bank_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_bank_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `clear_cash_in_hand_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_cash_in_hand_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `last_updated_ts` TIMESTAMP NULL DEFAULT NULL,
  `attachment_url` VARCHAR(200) NULL DEFAULT NULL,
  `bad_bank_loan_dept_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pen_shg_one_mem_reg_fee` DECIMAL(16,2) NULL DEFAULT NULL,
  `pen_shg_one_service_charges` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`g_ac_no`, `month`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_g_ac_by_txtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_g_ac_by_txtype` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_g_ac_by_txtype` (
  `month` VARCHAR(10) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `tx_type_id` INT(10) UNSIGNED NOT NULL,
  `amount` DECIMAL(16,2) NULL,
  PRIMARY KEY (`month`, `g_ac_no`, `tx_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`loan_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`loan_source` ;

CREATE TABLE IF NOT EXISTS `shg`.`loan_source` (
  `loan_source_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loan_source` VARCHAR(20) NOT NULL,
  `loan_source_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`loan_source_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`doc_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`doc_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`doc_type` (
  `doc_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `doc_type` VARCHAR(50) NOT NULL,
  `doc_for` VARCHAR(100) NOT NULL,
  `doc_category` VARCHAR(100) NOT NULL,
  `doc_desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`doc_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`ws_access_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`ws_access_code` ;

CREATE TABLE IF NOT EXISTS `shg`.`ws_access_code` (
  `access_code_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `access_code` VARCHAR(45) NOT NULL,
  `access_code_display` VARCHAR(45) NOT NULL,
  `access_code_category` VARCHAR(45) NOT NULL,
  `access_code_desc` VARCHAR(200) NULL DEFAULT NULL,
  `access_level` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`access_code_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`ui_access_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`ui_access_code` ;

CREATE TABLE IF NOT EXISTS `shg`.`ui_access_code` (
  `access_code_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `access_code` VARCHAR(45) NOT NULL,
  `access_code_display` VARCHAR(45) NOT NULL,
  `access_code_category` VARCHAR(45) NOT NULL,
  `access_code_desc` VARCHAR(200) NULL DEFAULT NULL,
  `access_level` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`access_code_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`doc` ;

CREATE TABLE IF NOT EXISTS `shg`.`doc` (
  `doc_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `doc_type_id` INT(10) UNSIGNED NOT NULL,
  `file` MEDIUMBLOB NOT NULL,
  `update_ts` TIMESTAMP NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `FK_Index1_idx` (`doc_type_id` ASC),
  CONSTRAINT `FK_Index1`
    FOREIGN KEY (`doc_type_id`)
    REFERENCES `shg`.`doc_type` (`doc_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_g_loan_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_g_loan_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_g_loan_ac` (
  `month` VARCHAR(10) NOT NULL,
  `g_loan_ac_no` BIGINT(20) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `b_group_ac_no` BIGINT(20) NOT NULL,
  `fund_type_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `loan_source_id` INT(10) UNSIGNED NOT NULL,
  `principle_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_principle_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `paid_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `installment_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pre_emi_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_interest_due_am` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`month`, `g_loan_ac_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`monthly_g_invt_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_g_invt_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_g_invt_ac` (
  `month` VARCHAR(10) NOT NULL,
  `g_invt_ac_no` BIGINT(20) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `b_group_ac_no` BIGINT(20) NOT NULL,
  `investment_type_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `investment_ac_name` VARCHAR(50) NULL DEFAULT NULL,
  `invt_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_invt_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`month`, `g_invt_ac_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`monthly_g_bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_g_bank_account` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_g_bank_account` (
  `month` VARCHAR(10) NOT NULL,
  `bank_account_no` BIGINT(20) NOT NULL,
  `g_ac_no` BIGINT(20) NOT NULL,
  `clear_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `subj_clearing_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `verified_balance_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `interest_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `penalty_charges_am` DECIMAL(16,2) NULL DEFAULT NULL,
  PRIMARY KEY (`month`, `bank_account_no`),
  INDEX `g_bank_acount_FKIndex2` (`bank_account_no` ASC),
  CONSTRAINT `g_bank_account_ibfk_20`
    FOREIGN KEY (`bank_account_no`)
    REFERENCES `shg`.`bank_account` (`bank_account_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`message_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`message_type` ;

CREATE TABLE IF NOT EXISTS `shg`.`message_type` (
  `message_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_type` VARCHAR(30) NULL,
  `sms_format` VARCHAR(200) NULL,
  `email_format` VARCHAR(500) NULL,
  `pass_key` BIGINT(20) NULL,
  PRIMARY KEY (`message_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`m_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`m_message` ;

CREATE TABLE IF NOT EXISTS `shg`.`m_message` (
  `m_ac_no` BIGINT(20) NOT NULL,
  `m_role_id` INT(10) UNSIGNED NOT NULL,
  `group_type_id` INT(10) UNSIGNED NOT NULL,
  `mobile_no` BIGINT(20) UNSIGNED NULL,
  `email` VARCHAR(50) NULL,
  `mobile_verified` INT(10) NULL,
  `email_verified` INT(10) NULL,
  `sms_sub_key` BIGINT(20) NULL,
  `email_sub_key` BIGINT(20) NULL,
  `last_updated` DATE NULL,
  PRIMARY KEY (`m_ac_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shg`.`mobile_m`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`mobile_m` ;

CREATE TABLE IF NOT EXISTS `shg`.`mobile_m` (
  `mobile_no` BIGINT(20) UNSIGNED NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL COMMENT '\"PENDING\",\"DONE\",\"UNDONE\",\"OVERDUE\",\"MISSED\",\"CANCELLED\"',
  `m_role_id` INT(10) UNSIGNED NOT NULL,
  `group_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`mobile_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`bank_ac_upload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`bank_ac_upload` ;

CREATE TABLE IF NOT EXISTS `shg`.`bank_ac_upload` (
  `upload_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `bank_account_no` BIGINT(20) NOT NULL,
  `amount` DECIMAL(16,2) NULL,
  `upload_date` DATE NULL,
  `file` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`upload_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_m_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_m_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_m_ac` (
  `month` VARCHAR(10) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `credit_rating` FLOAT NULL DEFAULT NULL,
  `saved_am` DECIMAL(16,2) NULL,
  `prov_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `returned_saved_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `returned_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `divided_profit_declared_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `divided_profit_paid_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `proj_int_on_loan_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `bad_dept_closed_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `rec_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `pending_penalty_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `last_updated_ts` TIMESTAMP NULL DEFAULT NULL,
  `planned_monthly_saving_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `prev_month_int_en_am` DECIMAL(16,2) NULL DEFAULT NULL,
  `no_of_loans` INT(10) NULL,
  `no_of_active_loans` INT(10) NULL,
  `meeting_attendance` FLOAT NULL,
  `meeting_attended` INT(10) NULL,
  `meeting_missed` INT(10) NULL,
  PRIMARY KEY (`m_ac_no`, `month`),
  INDEX `m_ac_FKIndex1` (`m_ac_no` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
