-- MySQL Script generated by MySQL Workbench
-- 01/21/15 02:39:08
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shg
-- -----------------------------------------------------
USE `shg` ;


-- -----------------------------------------------------
-- Table `shg`.`monthly_m_loan_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_m_loan_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_m_loan_ac` (
  `month` VARCHAR(10) NOT NULL,
  `m_loan_ac_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `recovery_period_id` INT(10) UNSIGNED NOT NULL,
  `fund_type_id` INT(10) UNSIGNED NOT NULL,
  `loan_calculation_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `loan_source_id` INT(10) UNSIGNED NOT NULL,
  `principle_am` DECIMAL(16,2) NULL,
  `pending_principle_am` DECIMAL(16,2) NULL,
  `rec_interest_am` DECIMAL(16,2) NULL,
  `proj_interest_am` DECIMAL(16,2) NULL,
  `installment_am` DECIMAL(16,2) NULL,
  `pre_emi_interest_am` DECIMAL(16,2) NULL,
  `pending_interest_due_am` DECIMAL(16,2) NULL,
  `rate_of_interest` FLOAT NULL,
  `startup_no_of_inst` INT(10) UNSIGNED NULL,
  `exp_no_of_inst` INT(10) UNSIGNED NULL,
  `no_of_inst_paid` INT(10) UNSIGNED NULL,
  `no_of_insall_late` INT(10) UNSIGNED NULL,
  `no_of_insall_missed` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`m_loan_ac_no`, `month`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`monthly_m_saving_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`monthly_m_saving_ac` ;

CREATE TABLE IF NOT EXISTS `shg`.`monthly_m_saving_ac` (
  `month` VARCHAR(10) NOT NULL,
  `m_saving_ac_no` BIGINT(20) NOT NULL,
  `m_ac_no` BIGINT(20) NOT NULL,
  `recovery_period_id` INT(10) UNSIGNED NOT NULL,
  `account_status_id` INT(10) UNSIGNED NOT NULL,
  `saved_am` DECIMAL(16,2) NULL,
  `cumulative_saved_am` DECIMAL(16,2) NULL,
  `saving_installment_am` DECIMAL(16,2) NULL,
  `total_int_en_am` DECIMAL(16,2) NULL,
  `current_fy_int_en_am` DECIMAL(16,2) NULL,
  `prev_month_int_am` DECIMAL(16,2) NULL,
  `returned_saved_am` DECIMAL(16,2) NULL,
  `returned_int_en_am` DECIMAL(16,2) NULL,
  `exp_no_of_inst` INT(10) UNSIGNED NULL,
  `no_of_inst_paid` INT(10) UNSIGNED NULL,
  `no_of_insall_late` INT(10) UNSIGNED NULL,
  `no_of_insall_missed` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`m_saving_ac_no`, `month`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`process_scheduler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`process_scheduler` ;

CREATE TABLE IF NOT EXISTS `shg`.`process_scheduler` (
  `process_scheduler_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  `done_by_member` BIGINT(20) NULL,
  `scheduler_key` BIGINT(20) NULL,
  PRIMARY KEY (`process_scheduler_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`schedule_process_error`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`schedule_process_error` ;

CREATE TABLE IF NOT EXISTS `shg`.`schedule_process_error` (
  `schedule_process_error_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `process_scheduler_id` INT NULL,
  `group_ac_no` BIGINT(20) NULL,
  `member_ac_no` BIGINT(20) NULL,
  `time` TIMESTAMP NULL,
  `error_job` VARCHAR(50) NULL,
  `error_message` VARCHAR(200) NULL,
  PRIMARY KEY (`schedule_process_error_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shg`.`process_scheduler_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shg`.`process_scheduler_sprint` ;

CREATE TABLE IF NOT EXISTS `shg`.`process_scheduler_sprint` (
  `process_scheduler_sprint_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `process_scheduler_id` INT NULL,
  `district_id` INT NULL,
  `sprint_index` INT NULL,
  `no_of_groups` INT NULL,
  `start_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  `info` VARCHAR(500) NULL,
  PRIMARY KEY (`process_scheduler_sprint_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
